Opetushallitus/ataru

- resources/templates/index.html
- spec/lomake_editori/clerk_routes_spec.clj
- spec/lomake_editori/middleware/cache_control_spec.clj
- spec/lomake_editori/test_utils.clj
- src/clj/lomake_editori/clerk_routes.clj
- src/clj/lomake_editori/middleware/cache_control.clj
Web browsers should be able to cache requests to all static resources (js and css files, images). Despite this we don't want browsers to cache resources indefinitely. In other words resources should be re-downloaded when needed.
There are 2 sides in this implementation:
1) Each static resource referred by the "index.html" is now tagged with a fingerprint HTTP GET parameter.
2) Server adds Cache-Control: no-cache, no-store or max-age=86400 header to each response, depending on the request type.
* The root page has no-cache.
* API calls have no-store.
* Static resources have max-age=86400.
> Cache requests to static resources

- dev/clj/user.clj
- project.clj
- src/clj/lomake_editori/core.clj
- src/clj/lomake_editori/db/migrations.clj
- src/clj/lomake_editori/system.clj
The REPL now uses reloaded.repl based workflow, so the server can be started from REPL with (reset), (start) and stopped with (stop).
Due to some technical difficulties (probably in the cljs side) the auto-reloading by Figwheel (when componentified) doesn't work. So this feature doesn't include that. So in practice one'll need to run the Figwheel Java side separately from terminal.
> Start using com.stuartsierra/component

- .gitignore
- README.md
- package.json
- project.clj
- resources/templates/test.html
- src/clj/lomake_editori/clerk_routes.clj
- test/cljs/lomake_editori/core_test.cljs
- test/cljs/lomake_editori/runner.cljs
This pull request adds capability to run UI tests. The solution is quite traditional setup where a browser first gets a "test.html" that acts as a runner page. The html page then bootstraps cljs.test based test suite and runs it inside an iframe.
> Capability to run UI tests in browser

- src/cljs/lomake_editori/core.cljs
- src/cljs/lomake_editori/editor/handlers.cljs
- src/cljs/lomake_editori/handlers.cljs
- src/cljs/lomake_editori/routes.cljs
User can now open an edit view to a specific form using a direct URL. The URL is like `/lomake-editori/#/editor/forms/:id` where `:id` is the ID of the form that should be shown to the user.
> Open an edit view to a form using a direct URL

- resources/log4j.properties
Change application log timestamp to unified format to make life easier for the log crawler.
> Set logging timestamp to ISO8601 in UTC

- project.clj
- spec/lomake_editori/soresu/component_spec.clj
- src/cljc/lomake_editori/soresu/component.cljc
- src/cljs/lomake_editori/editor/core.cljs
- src/cljs/lomake_editori/editor/handlers.cljs
This branch adds functionality to insert arbitrary form elements. New form elements can be added to the end of an element group or to the end of the form itself.
It shouldn't be possible to add elements into the middle of the form. Instead, there'll be a drag'n'drop feature in the future to make it possible to add elements to the middle of the form.
> Functionality to add arbitrary form elements

- resources/log4j.properties
Back to the local timezone, but retain format. It is easier for the developer or the support people to debug for errors.
> Use local timezone in logging

- src/cljs/lomake_editori/editor/component.cljs
- src/cljs/lomake_editori/editor/core.cljs
This feature makes text input fields to be rendered as they're defined in the app state (when rendering existing input fields). This includes: initial value of the input field, checking or unchecking of the required and multiple answers checkboxes.
Also, when user changes these values, they're stored to the internal app state.
> Render text input field according to what is set to app state

- project.clj
- spec/ataru/fixtures/form.clj
- spec/ataru/soresu/component_spec.clj
- src/clj/ataru/schema/clj_schema.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/hakija/form_view.cljs
- src/cljs/ataru/virkailija/editor/component.cljs
- Most schema changes are in soresu-lib, less hacking in ataru
- Move FormField :size under [:params :size] in order to validate schema.
> Proper schema validation

- resources/less/editor.less
- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
- test/cljs/unit/ataru/virkailija/editor/handlers_test.cljs
When user clicks remove link on a form element (a text field, wrapper element or whatnot), then the element is removed.
> Remove form element when user clicks the remove link

- src/clj/ataru/hakija/hakija_routes.clj
- src/clj/ataru/util/client_error.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/cljs_util.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
- src/cljs/ataru/hakija/core.cljs
- src/cljs/ataru/hakija/hakija_ajax.cljs
- src/cljs/ataru/virkailija/core.cljs
You can test this with e.g.:
src/cljs/ataru/hakija/application_handlers.cljs
(defn set-application-field [db [_ key value]]
+  (throw (js/Error. "Oops"))
(assoc-in db [:application :answers key] value))
> Log uncaught client errors of Hakija app to server log

- src/cljc/ataru/virkailija/editor/component_macros.cljc
- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/editor/core.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
When remove link is pressed either on a component or a component section, the target is removed with a fade-out effect.
The flow of removing a component works now like this:
1. User clicks remove link
2. An event handler that detects when the fade-out animation ends is installed onto the parent div containing the form component, or the whole wrapper component in case of a form section.
3. A `:hide-component` event is dispatched.
4. The `:hide-component` handler associates a `fading-out` status to the component to be removed.
5. The `component-with-fade-effects` associates the correct animation style to the component to be removed.
6. When the animation ends, the handler installed in part `2` of this list will be triggered. The handler function dispatches the `:remove-component` event.
7. …
> Fade out effect to components

- README.md
- project.clj
- src/clj/ataru/hakija/hakija_routes.clj
Fix swagger docs, somewhat. Used to not work and crash, now works, but UI has wrong spec.json URLs by default (needs to be manually overwritten; workaround in README.md).
> Fix swagger routes

- src/cljc/ataru/virkailija/editor/component_macros.cljc
- src/cljc/ataru/virkailija/soresu/component.cljc
- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
New components are faded-in to the form. The mechanism is pretty much the same than when fading out components (see https://github.com/Opetushallitus/ataru/pull/37).
> Fade in effects for new components

- resources/less/banner.less
- resources/less/editor.less
- resources/less/virkailija-banner.less
- src/clj/ataru/forms/form_store.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/editor/handlers.cljs
- src/cljs/ataru/virkailija/temporal.cljs
- src/cljs/ataru/virkailija/views/banner.cljs
- src/cljs/ataru/virkailija/virkailija_ajax.cljs
Do not overwrite changes & show error message when form has been changed in the background.
> Prevent concurrent editing

- src/cljc/ataru/virkailija/editor/component_macros.cljc
- src/cljs/ataru/virkailija/editor/component.cljs
When creating components with fade effects one now can use the `component-with-fade-effects` macro:
```clojure
(defn setup-fn [content path]
(let [some :local-state]
(component-with-fade-effects [path]
(fn [content path]
; create component here as usual))))
```
It's worth noting that the content (or soresu data object) must be the first argument. As good news it'll be changed later on to be a subscribe-based thing.
> Macro for creating component with fade effects

- resources/less/banner.less
- resources/less/editor.less
- resources/less/hakija.less
- src/clj/ataru/schema/clj_schema.clj
- src/cljc/ataru/virkailija/soresu/component.cljc
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_readonly.cljs
- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/editor/core.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
Implements dropdown question component. Looks like this (editor):
and (applicant):
Most of the ugliness in the implementation is due to how the empty option fields are created and shown (new options are added to empty input field at the _end_ of the list in the editor, and shown as the _first_ item in the applicant form).
> Dropdown component

- oph-configuration/config.edn.template
- spec/ataru/hakija/email_spec.clj
- src/clj/ataru/hakija/email.clj
- src/clj/ataru/hakija/hakija_routes.clj
In this implementation the recipient is hard-coded to a non-existing email address. The real recipient address must be set when we actually know who is the recipient.
> Send email confirmation when application is submitted

- config/defaults.edn
- oph-configuration/config.edn.template
- resources/templates/virkailija.html
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/editor/view.cljs
This branch adds working "preview application" link for the officer side. The "OPH" configuration mechanism is used to provide the public CLJS application configuration by placing it onto the root of the officer application's HTML using Selmer templating.
> Working "preview application" link

- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
- src/cljs/ataru/virkailija/soresu/component.cljs
Whenever a new form component is added, the input field used to define the component's name is automatically focused.
The implementation relies on the basic HTMLElement.focus() API call.
> Auto focus text field on new component

- spec/ataru/hakija/email_spec.clj
- src/clj/ataru/hakija/email.clj
- src/cljc/ataru/virkailija/component_data/person_info_module.cljc
This feature replaces random UUID keys in the perfon info module with hard-coded human-readable values like "email", "ssn", "first-name" etc.
Also binding to the person info module's email field is introduced: the recipient address of the confirmation email is now automatically picked from the person info module answers.
> Hard-coded keys and email bindings for person info module

- README.md
- src/clj/ataru/hakija/hakija_routes.clj
No more need for special instructions in README.md regarding Swagger UI. Just open the URL. API calls work directly too.
> Working Swagger UI for applicant side

- src/cljs/ataru/hakija/application_form_components.cljs
When an application with a dropdown is submitted, the value attribute from the option element of the dropdown will be submitted instead of the actual human-readable value.
This MIGHT be good behavior in the future when we hopefully have some kind of versioning in place for applications and therefore we have capability to map submitted value attributes to actual human-readable answers.
For example, when submitting a language, a `fi` value was submitted instead of `Finnish`. We can't unabigously map the `fi` to `Finnish` just based on the answer: the actual form might've been changed over time and the corresponding value to `fi` along with it.
But since we just want to have the human-readable answers on Excel, just submitting the actual human-readable value from the selected `option` …
> Show correct dropdown content in readonly view

- resources/less/hakija.less
- src/cljs/ataru/hakija/application_form_components.cljs
When input of a text *field* is invalid, hilight it with red color. The hilighting is only added to text fields as it's not sensible to have any kind of validation on text areas or dropdowns.
> Hilight invalid input on applicant side

- resources/less/application-common.less
- resources/less/hakija.less
- src/cljs/ataru/application_common/application_field_common.cljs
- src/cljs/ataru/application_common/application_readonly.cljs
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/banner.cljs
Use position-relative span as anchor which is -BANNER_HEIGHT above it's normal position.
Sections and fields work with this in chrome and firefox, fields work in IE, but sections for some reason do not in IE.
> Fix link anchors in application

- project.clj
- resources/db/migration/V1_11__Add_application_email_table.sql
- resources/sql/email-queries.sql
- spec/ataru/hakija/email_spec.clj
- src/clj/ataru/hakija/email.clj
- src/clj/ataru/hakija/email_store.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/clj/ataru/hakija/hakija_system.clj
Instead of immediately + synchronously attempting to send confirmation emails to users (and possibly failing), store them in the DB and have a separate mailer process attempt to deliver them via the Viestintäpalvelu API until successful.
> Persist and retry emails

- config/defaults.edn
- config/dev.edn
- oph-configuration/config.edn.template
- resources/less/editor.less
- resources/less/mixins.less
- src/clj/ataru/tarjonta_service/tarjonta_client.clj
- src/clj/ataru/tarjonta_service/tarjonta_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/editor/handlers.cljs
- src/cljs/ataru/virkailija/editor/view.cljs
- src/cljs/ataru/virkailija/routes.cljs
Shows when a form is currently linked to from tarjonta-app. Currently a bit hard to test, as the test environments are not fully up to date w/tarjonta. This will hopefully change soon.
The open periods for haku/hakukohde are not taken into account in this version of the functionality.
> Indicate form used by tarjonta

- resources/less/editor.less
- resources/less/general-style-settings.less
Fixes following IE specific issues:
* Language labels were not positioned correctly.
* Disabled IE's "clear input field contents" checkbox globally.
> IE layout fixes

- resources/less/hakija.less
- resources/sql/application-queries.sql
- resources/templates/email_confirmation_template.html
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/cache/cache_service.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/clj/ataru/virkailija/virkailija_system.clj
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/translations/application_view.cljc
- src/cljc/ataru/translations/email_confirmation.cljc
- src/cljs/ataru/application_common/application_readonly.cljs
- src/cljs/ataru/hakija/application.cljs
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
- test/cljs/unit/ataru/hakija/application_test.cljs
Remove person info module from application editing.
What has been done:
* Dynamically flag person info module questions as "uneditable" when loading application to edit, remove those answers' values
* Don't show those questions in the application edit view
* When submitting the edited application, flag uneditable answers and instead populate them from the previous submitted application.
> Remove person info module from application editing

- spec/ataru/fixtures/db/browser_test_db.clj
Without this change:
~~~
17-03-10 11:35:50 l991.core.reaktor.fi ERROR [ataru.log.audit-log:111] - Failed to create an audit log entry
clojure.core/partial/fn                                    core.clj: 2514
ataru.browser-tests/eval36180/fn/fn                spec/ataru/browser_tests.clj:   48
ataru.browser-tests/run-specs-in-virkailija-system                spec/ataru/browser_tests.clj:   22
ataru.fixtures.db.browser-test-db/init-db-fixture  spec/ataru/fixtures/db/browser_test_db.clj:   83
clojure.java.jdbc/db-transaction*                                    jdbc.clj:  598
clojure.java.jdbc/db-transaction*                                    jdbc.clj:  629
clojure.java.jdbc/db-transaction*                                    jdbc.clj:  613
ataru.fixtures.db.browser-test-db/init-db-fixture/fn …
> Fix browser tests emitting error log messages

- project.clj
- src/cljs/ataru/hakija/application_form_components.cljs
Fixes issues with informational elements on form: react warnings + line breaks.
Now uses Markdown for _all the things_, also HtmlSanitizer to remove dangerous HTML.
Some instructions for usage should probably be provided.
> Use Markdown + HtmlSanitizer to format form info fields

- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/util/language_label.clj
Fixes a bug where when editing application, the labels for uneditable fields (= person info module) were not stored correctly (turns out that in the database the format in answers is `{:label "Label for field"}` instead of `{:label {:en {"Label for field"}}}`).
Now store the labels for new answers correctly and also support the alternative/broken (but supported by form schema) format.
> Fix person field excel when editing english application

- src/clj/ataru/applications/excel_export.clj
- src/cljc/ataru/util.cljc
- src/cljs/ataru/cljs_util.cljs
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/hakija_readonly.cljs
- src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
- Shows "Liitepyyntö: <question>" in the column header.
- Shows "<filename> (<size>)" for each attachment in the cell. If an answer has multiple attachments, they are separated with a newline (still inside the same cell).
> Show useful info about attachments in the Excel export

- src/cljs/ataru/hakija/application_form_components.cljs
1. Add an attachment
2. Remove it
3. Add the same file again
4. → Nothing happens
5. Be sad 😢 
The file is added again.
This doesn't work on master because the HTML5 `input` component maintains its own `FileList` state. We need to make the element is re-rendered (and the internal state discarded) whenever we change our own state of attachments. 
I added a `key` to the element, based on its component-id and the count of attachment. This seems to fix things. I _think_ this is safe, because you can't update/replace attachments anymore, so all changes to the list of attachments inside this component means the count attachments changes. 
Please verify my logic 😨
> Fix adding a file, removing it, and adding it again

- resources/less/virkailija-common.less
- resources/less/virkailija-site.less
- src/cljs/ataru/virkailija/views.cljs
User sees  a "Ei oikeuksia" text-box instead of the tab content when there is no direct organization containing the required privileges to do anything useful in that tab (or "panel")
> Inform about insufficient rights

- config/defaults.edn
- config/dev.edn
- oph-configuration/config.edn.template
- project.clj
- resources/ataru-oph.properties
- src/clj/ataru/cas/client.clj
- src/clj/ataru/config/url_helper.clj
- src/clj/ataru/files/file_store.clj
- src/clj/ataru/hakija/application_email_confirmation.clj
- src/clj/ataru/hakija/background_jobs/email_job.clj
- src/clj/ataru/person_service/person_client.clj
- src/clj/ataru/tarjonta_service/tarjonta_client.clj
- src/clj/ataru/virkailija/authentication/auth.clj
- src/clj/ataru/virkailija/authentication/auth_routes.clj
- src/clj/ataru/virkailija/authentication/auth_utils.clj
- src/clj/ataru/virkailija/user/organization_client.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
Use java-utils/url.config to configure integration URLs (the beef is in `resources/ataru-oph.properties`).
Will probably require some tweaks to naming etc. to have the actual graph generation working as it should, but should probably tested in dev/QA first.
> Url properties config

- src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
If we don't put the filename in the `download` attribute on the `a` element, browsers will name the downloaded file after the last segment of the download URL, i.e. the UUID of the attachment. With this change, browsers will use the filename we've saved to the database instead.
This requires Chrome, Edge, Safari 10.1 (pre-release) or Firefox. Notably, IE does not support the `download` attribute at all. That means attachments will open inline in the IE window.
> Tell the browser attachments' real filenames

- src/clj/ataru/files/file_store.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
IE doesn't support the `<a download="filename.jpg">` HTML5 attribute, so we need to tell IE that the attachment should be downloaded and its name is `filename.jpg` via the Content-Disposition HTTP header. 
Depends on https://github.com/Opetushallitus/liiteri/pull/11 (merged)
> Fix attachment download on IE

- resources/less/hakija.less
- resources/less/vars.less
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
Tell the user in the upload UI how large attachments we support, and change the text color to red if the user tries to upload an attachment that is too large.
> Handle attachments that are too large

- resources/less/hakija.less
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
- src/cljs/ataru/hakija/banner.cljs
The error looks like this:
The error invalidates the form until the user clicks on the X to remove the file:
The validation text below the submit button was changed to better indicate the type of content in the popup: some fields are required and some fields can be optional but invalid. The attachment is listed in the popup with its label like any other question:
> Show error when trying to upload a prohibited file type

- resources/less/hakija.less
- resources/less/vars.less
- resources/spec/hakijaEditSpec.js
- spec/ataru/browser_tests.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/cljc/ataru/hakija/editing_forbidden_fields.cljc
- src/cljc/ataru/hakija/forbidden_fields.cljc
- src/cljc/ataru/schema/form_schema.cljc
- src/cljs/ataru/hakija/application.cljs
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
- src/cljs/ataru/hakija/hakija_readonly.cljs
Make application editing great again!
Can now edit person info fields, except for:
* SSN
* Nationality
* Birth date
Fields can not be flagged as `cannot-view` whose values cannot be seen when editing an application and `cannot-edit` whose values can be seen but not changed.
> Restore application editing

- project.clj
I don't know what the `/clojure` suffix was doing there. I tested that oppijanumerorekisteri integration still seems to work locally for me.
> Fix project.clj so that `lein ancient` works

- src/cljc/ataru/schema/form_schema.cljc
This was broken when we added the `final` key to attachments.
> Fix virkailija view of attachments

- resources/less/virkailija-banner.less
- src/clj/ataru/applications/excel_export.clj
- src/cljs/ataru/virkailija/application/handlers.cljs
- src/cljs/ataru/virkailija/routes.cljs
- src/cljs/ataru/virkailija/views/banner.cljs
Have answers to followup questions appear next to the "parent" question in the Excel export sheets.
There are still some weird corner cases when the original form has fields changed/removed, but they seem more or less inevitable with the myriad different possibilities that arise :(
> Fix followup ordering in excel export

- src/clj/ataru/files/file_store.clj
Safari likes to send attachment filenames in NFC form, which org.httpkit.client doesn't handle properly. We decompose the name here and things seem to work.
> Fix attachment filenames on Safari

- spec/ataru/hakija/validator_spec.clj
- src/clj/ataru/hakija/validator.clj
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/virkailija/component_data/person_info_module.cljc
- test/cljc/unit/ataru/fixtures/answer.cljc
- test/cljc/unit/ataru/fixtures/person_info_form.cljc
Previously ssn/birthdate/gender validation in person info module fields would succeed even with broken data, if at least one of the fields would validate correctly (and the broken data would be stored with the application). 
Now the validation is more fine-grained and will fail if broken data is encountered in the above fields.
> Fix ssn birthdate gender validation

- src/cljs/ataru/application_common/application_field_common.cljs
Consider a dropdown option `{:value "Red" :label {:fi "Punainen" :en "Red"}}`. Instead of displaying `Red` (the `:value` keyword) for the user in the readonly view, show either `Punainen` (Finnish label) or `Red` (English label).
Use the `:value` as a last resort.
> Use label instead of raw value in readonly

- src/cljs/ataru/application_common/application_field_common.cljs
- src/cljs/ataru/virkailija/application/view.cljs
When user searches applications eg. by date of birth, selects one application from the search results list and then closes this application using the close check mark on the left side of the view, do not lose all the search results.
> Do not close the application list when closing a single application

- resources/less/hakija.less
- resources/spec/hakijaEditSpec.js
- resources/spec/hakijaSpec.js
- resources/spec/virkailijaEditorSpec.js
- src/cljc/ataru/util.cljc
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/hakija_readonly.cljs
- src/cljs/ataru/hakija/subs.cljs
- src/cljs/ataru/virkailija/editor/component.cljs
- src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
Includes:
* Support followup questions in a single choice list.
* Animations for all followup questions (fade in when opened).
Does not include:
* Fix for the adjacent text fields as followup question.
> Support followup questions in single choice list

- resources/db/migration/V1_49__Add_application_feedback_table.sql
- resources/less/hakija.less
- resources/less/mixins.less
- resources/less/vars.less
- resources/sql/application-queries.sql
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/flowdock/flowdock_client.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/translations/application_view.cljc
- src/cljs/ataru/hakija/application_handlers.cljs
- src/cljs/ataru/hakija/application_view.cljs
- src/cljs/ataru/hakija/hakija_readonly.cljs
Implemets a feedback form, shown after an application is submitted (should maybe have a possibility to send feedback also before submitting). Things to note:
* Posts to Flowdock, needs flow tokens configured for each environment (currently there exists only a test flow for test environments)
* Does not have Swedish localizations yet – need to be added before production use
> Feedback form

- resources/sql/statistics-queries.sql
- resources/templates/dashboard.html
- src/clj/ataru/cache/cache_service.clj
- src/clj/ataru/core.clj
- src/clj/ataru/statistics/statistics_service.clj
- src/clj/ataru/statistics/statistics_store.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
A proof-of-concepty dashboard for gleaming information about the system's internals. Currently shows graphs of number of applications submitted by the past month, week and day (if any exist). The front-end is especially quick'n'dirty while the actual design of the dashboard is created.
Can be found at /lomake-editori/dashboard.
> Virkailija dashboard

- resources/less/editor.less
- src/cljs/ataru/virkailija/editor/component.cljs
In editor view when removing (some) components it did:
- fades out the component while sliding OVER the component above -> slides under
- some elements left the wrapper element border as is while fading out -> don't anymore
> Fix component fadeout animation.

- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_form_service.clj
- src/cljc/ataru/virkailija/component_data/component.cljc
- src/cljs/ataru/hakija/application_handlers.cljs
Editing applications with old forms was broken due to them not having the `hakukohteet` component in the form content. This fixes the issue by dynamically adding the component to the forms from which it is missing (both on client side and during validation on the server).
> Fix application editing with old forms

- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
Changes:
* Allow multiple attachments to be uploaded in separate "upload processes".
* Don't allow attachment with same name and size to be uploaded multiple times.
> Fix attachment upload

- resources/templates/hakija.html
- resources/templates/virkailija.html
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/translations/application_view.cljc
- src/cljc/ataru/virkailija/component_data/component.cljc
- src/cljs/ataru/application_common/fx.cljs
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/application_hakukohde_component.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
Various accessibility improvements. Including
* Missing localizations (sv/en)
* `for`-attributes for label elements
* HTML page titles
* Initial aria-attributes for elements
This is an initial pass, at least the following things should still be worked on:
* `aria-role` attributes for all non-form elements
* `aria-invalid` attributes for elements not passing validation
> Accessibility improvements

- resources/less/virkailija-common.less
- src/cljs/ataru/virkailija/application/view.cljs
Add generic tooltip style (using data-property) and use it to show whole name of application editor when hovering initials:
> HLE-54 see whole name in application edit log

- spec/ataru/fixtures/application.clj
- spec/ataru/fixtures/form.clj
- spec/ataru/hakija/hakija_routes_spec.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_routes.clj
When editing hakemus check field editability with backend logic, don't rely on request body data (haaahaa curlers!)
> Hakemus edit loopholes

- resources/spec/virkailijaHakemusEditSpec.js
- spec/ataru/hakija/hakija_routes_spec.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/cljc/ataru/application/field_types.cljc
- src/cljc/ataru/schema/form_schema.cljc
- src/cljs/ataru/hakija/application.cljs
- src/cljs/ataru/hakija/subs.cljs
- Fix hakemus not opening for editing
- Fix fields with no answer in backend being editable since the non-existing answer couldn't obviously be flagged as uneditable.
> Only attachments editable fixes

- src/cljs/ataru/virkailija/editor/component.cljs
Previously the link in the markdown info popup did now work, as clicking it would blur the related input box, hiding said popup (and link) before the `onClick` event would fire. Now use the `mouseDown` event to intercept click before hiding the element.
> Hack-ish fix for clicking markdown help link

- resources/sql/application-queries.sql
- src/clj/ataru/applications/application_access_control.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/schema/form_schema.cljc
Vanha secure kontekstissa oleva API on jätetty tarkoituksella olemaan, jotta tämän muutoksen voisi viedä tuotantoon ilman, että vanhaa APIa käyttävä Omatsivut hajoaa.
> Authenticated Omatsivut API

- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/log/audit_log.clj
Otetaan logitettavasta uudesta asiasta pois :content ja :answers, eli hakemuksilta ja lomakkeilta isot asiat veke auditlogitettaessa.
> Don't auditlog content or answers from new forms and applications.

- resources/sql/application-queries.sql
- spec/ataru/applications/application_store_spec.clj
- spec/ataru/fixtures/db/browser_test_db.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/hakija/hakija_application_service.clj
When a question is removed from form, remove possibly orphaned attachment
reviews if application is updated.
> Remove orphan attachment reviews

- src/cljs/ataru/virkailija/handlers.cljs
Email template changes are saved (manually) by the user. Flasher shouldn't activate from updates to preview iframe.
> Deactivate flasher fx while (email) template editor is visible

- src/clj/ataru/tarjonta_service/tarjonta_service.clj
- src/cljc/ataru/schema/form_schema.cljc
- src/cljs/ataru/virkailija/application/application_subs.cljs
Tarjoaja-oids was not enough information to check if massamuokkaus should be visible. Some organisations have multiple organisation oids.
> HLE-474 : Hiding massamuokkaus if yhteishaku (instead of tarjoaja oids)

- dev-resources/sql/anonymizer-application-queries.sql
- dev/clj/ataru/anonymizer/core.clj
- Use correct person-oid key when parsing anonymous persons file.
- Get persons with person OID, not with application OID.
> Fix issues found when testing anonymization

- resources/sql/application-queries.sql
Jos hakemuksen muokkauksessa sekä lisätään hakukohde, että muokataan
liitepyynnön vastausta, tulee tarve lisätä rivi
application_hakukohde_attachment_reviews tauluun vaikka kyseessä on muuttunut
liitepyynnön vastaus.
> Liitepyyntömerkintä rivi syntyy päivityksessä

- dev/clj/ataru/anonymizer/core.clj
* Correct birth date for anonymized person
* Use first name as preferred name
* Use anonymized email in answers and application metadata
* Use “Helsinki” as home town in all anonymized applications, instead of non-existent home town
> Fixes to anonymization

- src/clj/ataru/email/application_email_confirmation.clj
When building a confirmation email, if attachment does not have the name (label)
for given language, use the labels in fallback language, in this order:  fi, sv, en.
> BUG-2048 Use fallback language for attachments' labels

- resources/db/migration/V1_113__attachment_review_rename.sql
- spec/ataru/applications/application_store_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/cljc/ataru/application/review_states.cljc
- src/cljc/ataru/translations/texts.cljc
- test-postgres/Dockerfile
Kolmen commitin viestien pitäisi selittää asia aika tyhjentävästi.
Nimesin myös kannassa liitteen tilan "incomplete" muotoon "attachment-missing", koska vanhan "Puutteellinen"-tilan merkitys muuttui samassa muotoon "Liite puuttuu."
> HLE-1017 :  liitepyyntojen kasittelymerkintojen muutokset

- resources/less/hakija.less
- resources/less/virkailija-application.less
- src/cljs/ataru/hakija/application_form_components.cljs
Pitkät tiedostonimet näkyvät liian leveänä.
Rivitetään tyyleillä (break-word) missä mahdollista, muuten lyhennetään näytettyä nimeä koodissa.
> BUG-2077  ui overflow

- Makefile
- bin/check-tool-version.sh
This pull request introduces version checks to Makefile. This should prevent issues where f.ex too old nodejs causes hard to debug issues (for example, eslint refusing to run)
> Introduce stricter version checks to makefile

- Makefile
- Makefile.md
- project.clj
Tests run locally were using incorrect test database due to missing test profile. This caused tests to clobber the development database, which is usually not desirable.
The Makefile is also taught to run the different parts of test execution, that were previously only in `bin/cibuild.sh`.
> Fix incorrect database use in tests; introduce more granular test Makefile API 

- oph-configuration/config.edn.template
- resources/ataru-oph.properties
- resources/less/vars.less
- resources/less/virkailija-kevyt-valinta.less
- resources/less/virkailija-site.less
- spec/ataru/user_rights_spec.clj
- src/clj/ataru/applications/application_access_control.clj
- src/clj/ataru/haku/haku_service.clj
- src/clj/ataru/hakukohde/hakukohde_service.clj
- src/clj/ataru/organization_service/session_organizations.clj
- src/clj/ataru/organization_service/user_rights.clj
- src/clj/ataru/tarjonta_service/tarjonta_service.clj
- src/clj/ataru/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu_client.clj
- src/clj/ataru/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu_protocol.clj
- src/clj/ataru/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu_service.clj
- src/clj/ataru/virkailija/authentication/auth.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/clj/ataru/virkailija/virkailija_system.clj
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/translations/texts.cljc
- src/cljc/ataru/user_rights.cljc
- src/cljs/ataru/virkailija/application/handlers.cljs
- src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_handlers.cljs
- src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs
- src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_view.cljs
- src/cljs/ataru/virkailija/application/view.cljs
- src/cljs/ataru/virkailija/editor/handlers.cljs
- src/cljs/ataru/virkailija/views/banner.cljs
Alustava ei-toiminnallinen käyttöliittymä tulevalle kevytvalinta -ominaisuudelle.
* Sisältää integraation atarun virkailijasovelluksen taustajärjestelmästä valintalaskentakoostepalveluun.
* Alustavan käyttöliittymäluonnoksen (kuva ohessa).
* Logiikan, jolla tarkistetaan koska kevytvalinnan käyttöliittymä näytetään (haulla ei sijoittelua, yhdelläkään valitulla hakukohteella ei valintalaskentaa).
Asennettu pallero-ympäristöön.
> HLE-1068: valinnan tila hakemuspalvelussa

- resources/spec/virkailijaEditorSpec.js
- spec/ataru/fixtures/db/browser_test_db.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/editor/handlers.cljs
- test/cljs/unit/ataru/virkailija/editor/handlers_test.cljs
The problem was that copied contents (form component) gets lost when "form details view" is closed, and the list of forms is reloaded from server. Because of that, the paste was failing. The solution is to remember the copied contents separately, not to rely on it being available in the list of forms.
> BUG-2082 copy/paste lomakeosio sometimes fails

- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/hakija/banner.cljs
- test/cljs/unit/ataru/hakija/banner_test.cljs
- test/cljs/unit/ataru/unit_runner.cljs
According to Minea's specification: 
Halutaan että kun hakuaikaa on jäljellä 24h lomakkeen ylälaitaan ilmestyy teksti hakuaikaa jäljellä alle vuorokausi, sitten seuraavat: hakuaikaa jäljellä alle tunti, alle 45 min, alle 30min ja alle 15 min.
> BUG-2060 Update remaining application time text

- resources/less/virkailija-kevyt-valinta.less
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/application/kevyt_valinta/view/virkailija_kevyt_valinta_common_view.cljs
- src/cljs/ataru/virkailija/application/kevyt_valinta/view/virkailija_kevyt_valinta_julkaisun_tila_view.cljs
Muutetaan julkaisun tilan tarkistumerkki ns. liukukytkintyyppiseksi valinnaksi. Ks. oheiset kuvat.
> HLE-1135: muutetaan tarkistusmerkki liukukytkimeksi

- src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs
Käyttäjä ei näe kevytvalinnan valinnan tilassa tiloja "perunut", "peruutettu" tai "peruuntunut".
Mikäli senhetkinen valinnan tila valinta-tulos-servicessä on jokin näistä, juuri tämä kyseinen valinta näytetään. Toisin sanoen, mikäli käyttäjä muuttaa valinnan tilan jostain näistä kolmesta arvosta joksikin muuksi, ei arvoa voi enää vaihtaa takaisin yhteenkään näistä.
> HLE-1136: ei näytetä valinnan tiloja "perunut", "peruutettu", "peruuntunut"

- config/defaults.edn
- config/dev.edn
- config/test.edn
- oph-configuration/config.edn.template
- resources/sql/application-queries.sql
- src/clj/ataru/applications/application_store.clj
- src/cljc/ataru/config.cljc
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/hakija/application_view.cljs
- src/cljs/ataru/virkailija/config.cljs
- src/cljs/ataru/virkailija/core.cljs
Muokkauslinkin voimassaolo muutetaan 30 päivästä 14 päivään. Lisäksi jokainen kyseistä arvoa käyttävä kohta lukee tiedon konfiguraatiosta aiemman kovakoodauksen sijaan.
> HLE-1119: muokkauslinkin voimassaolo 14 päivään

- spec/ataru/fixtures/form.clj
- spec/ataru/hakija/hakija_routes_spec.clj
- src/clj/ataru/applications/application_store.clj
Note that hakija API still responds with hidden attachments, it is the client (GUI) which is supposed to hide them.
> BUG-2105 Do not include hidden attachments to application*

- src/cljs/ataru/hakija/banner.cljs
- test/cljs/unit/ataru/hakija/banner_test.cljs
When hakuaika-end or time-diff are nil, don't show anytext in the banner.
> BUG-2130 Handle the nil cases

- src/cljs/ataru/hakija/application_form_components.cljs
Ei siitä sen kummmempaa, varmaan refaktoroinnin vauhtihuumassa vain unohtunut alunperin. Tällä toimii:
> BUG-2136 Pass optional error params to translation function to ensure correct formatting

- resources/ataru-oph.properties
- src/clj/ataru/virkailija/authentication/auth.clj
- src/clj/ataru/virkailija/authentication/auth_routes.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/error/view.cljs
- src/cljs/ataru/virkailija/routes.cljs
- src/cljs/ataru/virkailija/views.cljs
The login failure in this context means erroneous CAS ticket handling or other such technical issues, not "wrong password" kind of login issues.
---
Tässä on vielä epäselvyytenä mihin kohtiin tämä pitäisi laittaa näkymään ja missä kohdin olemassaoleva uudelleenohjaus kirjautumiseen on OK. Itse virhehän näyttää tältä:
> BUG-2100: Redirect user to generic error page on technical login failure

- resources/sql/application-queries.sql
Testaten hakuoidilla `1.2.246.562.29.36339915997` (kevään 2020 toinen kk-yhteishaku).
Ennen:
```
QUERY PLAN
Result  (cost=5.00..5.05 rows=1 width=1) (actual time=8044.031..8044.031 rows=1 loops=1)
InitPlan 1 (returns $3)
->  Nested Loop Anti Join  (cost=1.41..151419.20 rows=42167 width=0) (actual time=8044.027..8044.027 rows=1 loops=1)
->  Nested Loop  (cost=0.98..113909.47 rows=63251 width=43) (actual time=8043.986..8043.986 rows=1 loops=1)
->  Index Only Scan using application_hakukohde_reviews_application_idx on application_hakukohde_reviews ahr  (cost=0.56..39996.04 rows=115673 width=35) (actual time=0.013..656.147 rows=96896 loops=1)
Index Cond: (requirement = 'selection-state'::text)
Heap Fetches: 95576
->  Index Scan using applications_key_idx on applications a  (cost=0.42..0.59 …
```
> HLKE-1196 : Tehokkaamman planin tuottava kysely

- src/clj/ataru/virkailija/virkailija_routes.clj
Näin esimerkiksi 404 source map-tiedostoille ei tuota poikkeusta atarun
lokille.
> Palauta dev-ympäristössä proxy-request-http-kutsujen virheet kutsujalle

- .clj-kondo/config.edn
- .gitignore
- spec/ataru/organization_service/organization_service_spec.clj
- src/clj/ataru/cache/caches.clj
- src/clj/ataru/hakija/hakija_system.clj
- src/clj/ataru/organization_service/organization_client.clj
- src/clj/ataru/organization_service/organization_service.clj
- src/clj/ataru/tarjonta_service/tarjonta_service.clj
- src/clj/ataru/virkailija/virkailija_system.clj
Refaktorointi, joka poistaa clojure.cachen ja korvaa sen Caffeinella (eli koodinsisäisesti in-memory cachella) organisaatiohierarkiahauissa.
> BUG-2128: organization service caching

- src/clj/ataru/organization_service/organization_client.clj
This is a revert of https://github.com/Opetushallitus/ataru/commit/0f8e32709b0b2c6378e7d53d8168914b39a199ce https://github.com/Opetushallitus/ataru/commit/2466b51222dca43029e3584f78523ce1d32b63ab
> BUG-2128: remove special case for oph-organization check

- .gitignore
- resources/sql/application-queries.sql
When no other query parameters are given, it takes a lot of effort to find out whether applications were modified after given date/time, because it unnecessary uses UNION operator. The solution is to use the more efficient EXISTS clauses.
> OY-372 Optimize yesql-suoritusrekisteri-applications

- cypress/.eslintrc
- cypress/dropdown.ts
- cypress/hakijanNakyma.ts
- cypress/integration/peruskoulunArvosanatSpec.ts
- cypress/lomakkeenMuokkaus.ts
- cypress/testit/arvosanat/peruskoulunArvosanatOsionAidinkielenVaihtaminen.ts
- cypress/testit/arvosanat/peruskoulunArvosanatOsionTayttaminenHakijana.ts
- cypress/testit/hakemuksenLahettaminen.ts
- resources/less/arvosanat-hakija.less
- src/clj/ataru/hakija/validator.clj
- src/cljc/ataru/component_data/arvosanat_module.cljc
- src/cljc/ataru/component_data/person_info_module.cljc
- src/cljc/ataru/schema/child_validator_schema.cljc
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/arvosanat/arvosanat_components.cljs
- src/cljs/ataru/hakija/arvosanat/arvosanat_render.cljs
- src/cljs/ataru/hakija/components/dropdown_component.cljs
- src/cljs/ataru/hakija/hakija_readonly.cljs
- src/cljs/ataru/hakija/rules.cljs
- src/cljs/ataru/hakija/schema.cljs
Kun hakija valitsee henkilötietomoduulista äidinkielekseen ruotsin, näytetään A1- ja A2 -kielet, muussa tapauksessa A1- ja B1 -kielet.
> HLE-1098: kielten oppiaineiden muuttuminen hakijan äidinkielen mukaan

- src/cljc/ataru/collections.cljc
- src/cljc/ataru/component_data/component.cljc
- src/cljc/ataru/component_data/person_info_module.cljc
- src/cljc/ataru/number.cljc
- src/cljs/ataru/virkailija/editor/handlers.cljs
- test/cljs/unit/ataru/collections_test.cljs
This means that editing and reorganizing the dropdown will not affect the existing values. Whiile new elements will get new, unique values. When creating new dropdown in editor, the values will start from 0, which is like old behaviour.
> BUG-2143 dropdown values will be set only when they are not already given

- src/clj/ataru/hakija/hakija_application_service.clj
Ennen HLE-1180 muutoksia sellaisia vastauksia joiden value oli not-empty ei
tallennut tietokantaan ollenkaan. Tämän takia edited-cannot-edit-questions
joutuu käsittelemään erikseen tilanteen jossa vastaus löytyy kaikkien
vastauksien joukosta, ja tilanteen jossa sitä ei löydy.
> Käsittele puuttuvat vanhat tyhjät vastaukset

- cypress/asetukset.ts
- cypress/hakijanNakyma.ts
- cypress/lomakkeenMuokkaus.ts
- cypress/tekstikentta.ts
- cypress/testit/henkilotietoModuulinTayttaminen.ts
Tämä toivottavasti korjaa esim rikkinäisen "Testilomake"-tekstin ongelman Cypress-testeistä.
> Varmempi tekstinsyotto Cypressilla

- project.clj
- src/clj/ataru/cache/caches.clj
- src/clj/ataru/cas/client.clj
- src/clj/ataru/db/migrations.clj
- src/clj/ataru/hakija/hakija_system.clj
- src/clj/ataru/virkailija/virkailija_system.clj
It means `caller-id` has to be provided with each instance of `CasClient`
> HLE-1258 Update scala-cas_2.12 to version 2.0.0

- src/cljc/ataru/collections.cljc
- src/cljc/ataru/component_data/component.cljc
- src/cljs/ataru/virkailija/editor/handlers.cljs
Pari käännösvirhettä poistettu. Tuplasti esiintyvä määrittely ja dropdown-option alustus arvosanat-modulissa. Tämä liittyy dropdown-muutokseen #1047.
> Korjaa cljs käännosvirheet

- src/cljs/ataru/hakija/application_handlers.cljs
Let the orphan attachment removal process take care
of the attachments. This means that if an attachment
is removed in the UI but the application is not saved,
the attachment is not really removed.
> OY-386 Remove attachments after saving application.

- resources/sql/application-list-query.sql
This is to prevent the first part of a two-part last name
getting combined with the first name when constructing the
search tokens, which was effectively breaking the search.
> BUG-2222 Concat first and last names with a space in between

- src/clj/ataru/koodisto/koodisto_db_cache.clj
Oppilaitosnumero-koodiston koodit saattavat olla relaatiossa usean
oppilaitostyyppi-koodin kanssa, joten toisteiset oppilaitosnumero-koodit tulee
poistaa.
> Palauta vain yksi jokaista koodi

- resources/less/arvosanat-hakija.less
- resources/less/hakija.less
- resources/less/vars.less
Tyylimuutos, lisätty kontrastia saavutettavuusspeksien mukaiseksi arvosanataulukkoon sekä muutamaan muuhun tiketin kuvankaappauksissa näkyvään kohtaan missä on harmaata tekstiä valkoisella taustalla.
> OY-4034 lisätty kontrastia 

- spec/ataru/hakija/application_validators_spec.clj
- src/cljc/ataru/hakija/application_validators.cljc
- src/cljs/ataru/hakija/application_handlers.cljs
- test/cljs/unit/ataru/hakija/application_validators_test.cljs
https://jira.eduuni.fi/browse/OY-4083
- Varmistutaan, että liite poistuu oikeasti values-taulukosta kun se poistetaan kälissä
- Corner case: liitteen poistaminen virhetilanteissa saattaa jättää kentän valueksi vektorin jossa on yksi tai useampi tyhjä stringi. Validaattori nappasi aiemmin vain tyhjät vektorit ja tyhjät stringit, nyt myös vektorin jossa sisällä vain tyhjiä stringejä
> OY-4083 Remove attachment data properly

- resources/less/button-component.less
- resources/less/dropdown-component.less
- resources/less/hakija.less
- src/cljs/ataru/application_common/components/dropdown_component.cljs
Previously the user wasn't able to fill in the grade sheet only by using keyboard navigation. With this PR it's possible via tabbing + enter/space (including a focus indicator everywhere)
> OY-4123 Allow navigating and selecting grades with keyboard

- cypress/hakijanNakyma.ts
- cypress/integration/hakemuksenValidoinnitSpec.ts
- src/cljc/ataru/hakija/application_validators.cljc
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/hakija/subs.cljs
Huoltajien spostisoite-kentissä näkyy nyt virheilmoitus ja väärän muotoisesta osoitteesta, ja kenttä menee punaiseksi.  Korjattu virhetyylin puuttuminen myös ei-pakollisessa hakijan sähköpostikentässä (2. asteen yhteishaun lomake)
Cypress-testipohja hakulomakkeen validoinneille.
> Oy 4171 huoltajien spostisoite-kenttään virheilmoitus väärän muotoisesta spostista

- .gitignore
- README.md
- spec/ataru/email/application_email_spec.clj
- spec/ataru/email/email_fixtures.clj
- src/clj/ataru/email/application_email.clj
Previously, if URLs in sent e-mails had pairs of underscores, they could be treated as Markdown, and vanish due to Markdown conversion and the following HTML sanitization.
After this change, the underscores in matched URL-like strings are escaped and not considered as Markdown control characters. The matching should be "good enough" for the purpose.
The attachment address URLs in e-mails also now undergo the same HTML styling and sanitization as the rest of the links.
> OY-4221 Do not treat underscores in full URLs in e-mail content as Markdown

- config/dev.edn
- config/test.edn
- oph-configuration/config.edn.template
- resources/sql/form-cleanup-queries.sql
- resources/templates/email_background_job_failed.html
- spec/ataru/background_job/job_execution_spec.clj
- spec/ataru/background_job/job_spec.clj
- src/clj/ataru/background_job/email_job.clj
- src/clj/ataru/background_job/job_execution.clj
Korjattu vanhat lomakkeet siivoavan background jobin sql ja lisätty sähköpostin lähetys konfiguroitaviin osoitteisiin jos tausta-ajo epäonnistuu lopullisesti.
> Oy 4223 lomakesiivous-jobin korjaus ja häläri failanneesta jobista

- .gitignore
- resources/less/hakija.less
- src/cljs/ataru/hakija/application_view.cljs
- src/cljs/ataru/hakija/banner.cljs
After submitting application, Voiceover did not always read the submit confirmation, nor the request for feedback. Try to instruct it to do so here.
Unfortunately this ended up being a bit of a cargo cult programming type solution, as it's quite hard to make real sense of the focus / reading order at this point in the application flow. However, this seems to solve the reported problem, a least based on repeated manual tests.
> OY-4179 Fix Voiceover focus / reading order after submitting application

- cypress/integration/hakemuksenValidoinnitSpec.ts
- cypress/testit/lomake-elementit/tekstikentta/virkailija/lomakkeet/tekstialue.ts
- cypress/testit/lomake-elementit/tekstikentta/virkailija/lomakkeet/tekstikentta.ts
- spec/ataru/applications/application_store/answers_db_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/cljs/ataru/hakija/application_form_components.cljs
- src/cljs/ataru/virkailija/editor/components/repeater_checkbox_component.cljs
- src/cljs/ataru/virkailija/editor/components/text_component.cljs
- src/cljs/ataru/virkailija/editor/components/toolbar.cljs
Trimmaus tekstikentille ja tekstialueelle backendiin ja myös käliin, jotta saadaan validaatiot käyttäytymään halutulla tavalla.
Cypress-testit eri tyyppisten tekstikenttien trimmauksille.
> Oy 4160 hakemuksen tekstivastausten trimmaus

- src/cljs/ataru/application_common/application_field_common.cljs
Turn (sub)strings that look like URLs to links in virkailija read-only view. Using a simple & unsophisticated RegEx, because we don't actually need to validate anything.
> OY-4237 Turn URLs to links in virkailija hakemus view

- config/dev.edn
- config/test.edn
- oph-configuration/config.edn.template
- spec/ataru/background_job/job_execution_spec.clj
- src/clj/ataru/background_job/job_execution.clj
- Allow enabling / disabling job failure mails per environment
- Add job id to failure mails to allow finding it from the db more easily
- Add full trace information to error msgs containing throwables / exceptions (log, database, e-mail)
> OY-4266 Job failure mail config + job error reporting improvements

- src/cljc/ataru/preferred_name.cljc
- test/cljc/unit/ataru/fixtures/first_name.cljc
Ataru has a looser validation than ONR for preferred names ("kutsumanimi"), which results in some ONR create / update operations failing due to validation errors. 
This PR aims to make Ataru validation equal or stricter to ONR. What stays stricter is case handling: ONR lowercases everything before comparison, Ataru still requires exact case / capitalization.
ONR validator: https://github.com/Opetushallitus/oppijanumerorekisteri/blob/c80de1bf06aa6d1251104d269a5f2fc43d22c41f/oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/validators/KutsumanimiValidator.java
> OY-4276 Rewrite preferred name validation to closer match ONR

- spec/ataru/email/email_util_spec.clj
- src/clj/ataru/email/application_email.clj
- src/clj/ataru/email/email_util.clj
- src/clj/ataru/information_request/information_request_service.clj
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/application/application_review_view.cljs
- src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_view.cljs
- src/cljs/ataru/virkailija/application/mass_information_request/virkailija_mass_information_request_view.cljs
- Limit freely definable e-mail subject to 120 characters in the UI, add note about the limit where there previously was none
- Hard limit subject to 255 characters in the backend so that application id never gets truncated
> OY-4277 email subject char limit

- src/clj/ataru/applications/suoritus_filter.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/application/handlers.cljs
There was an error in the UI when loading applications from jatkuva haku / toisen asteen yhteishaku, because the API that fetches school data used haku end year for fetching, and those particular ones don't necessarily have that.
After this PR, application created year is used for jatkuva haku & toisen asteen yhteishaku. We pass the application created date as a parameter for now to avoid extra roundtrip to database - if more application info is needed within the endpoint later, application OID + database query would be a better idea.
> OY-4357 Use application created at instead of haku end year for jatkuva haku school data

- resources/less/virkailija-application.less
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/application/application_review_view.cljs
Resending confirmation mail to applicant also resends it to guardians in case there are guardian e-mails. Indicate that, and the guardian e-mails in UI whenever defined.
> OY-4303 indicate possible guardians in resend modify link UI

- src/cljs/ataru/hakija/application.cljs
- src/cljs/ataru/hakija/application_handlers.cljs
- test/cljs/unit/ataru/hakija/application_test.cljs
Default language (äidinkieli) should follow form language selection: fi -> fi, sv -> sv, en -> empty.
> OY-4302 application default language

- spec/ataru/email_spec.clj
- src/cljc/ataru/email.cljc
Disallow comma in the local part of the e-mail, because people often typo that and fail to get e-mail. The domain part already has tighter validation so that doesn't need to be changed.
The e-mail validation is quite relaxed in general, so it still allows a lot of characters not allowed in RFC. We decided to go with an incremental / micro change, and perhaps rewrite validation or use a validation library later.
>  Disallow comma in e-mail address validation

- .husky/post-commit
- Makefile
- bin/cibuild.sh
- package-lock.json
Aiemmin package-lock.json on pari kertaa vaihtunut, ilmeisesti vahingossa, formaattiversioiden 1 ja 2 välillä, ja lisäksi package.json ja package-lock.json eivät olleet edes synkassa niin, että npm ci olisi onnistunut.  Tämä PR:
1. fiksaa package-lock.jsonin vastaamaan package.json:a
2. varmistaa CI:ssä, että nämä vastaavat toisiaan
3. varoittaa kehittäjiä, jos package-lock.jsonin versio on muuttunut.
Laajemmassa mielessä toki atarun ikimuinainen Node-versio 12 ja varsinkin npm-versio 6 pitää varmasti päivittää, mutta jos tätä ei haluta vielä tehdä, niin tämä PR on hyödyllinen jottei package-lock.json ole lähdekoodissa ihan turhaan.  (Tällä hetkellä lokaali build ja CI eivät kummatkaan piittaa siitä vaan ylikirjoittavat sen, joten se on turha gitissä.)
> Mekanismit varmistamaan ettei package-lock.json:a muutella vahingossa

- .gitignore
- resources/less/hakija.less
- src/cljs/ataru/hakija/application_view.cljs
Make demo overlay get focus priority, so the user can close it easily with keyboard navigation. Before this change, all the numerous form elements hidden behind the modal were first in focus order.
~~(Note: turns out actively hiding the parent container(s) with visibility / display / aria-hidden does not remove the focusable elements from accessibility tree, they would probably need to be temporarily "deactivated" recursively. So now they still exist, they're now just after the modal in tab order.)~~
The initial trick didn't work for the screen reader, so now the application is conditionally rendered only when demo dialog is not on the screen.
> OY-4492 mark demo overlay as alert dialog to fix focus issue

- src/clj/ataru/email/application_email.clj
- src/clj/ataru/email/application_email_jobs.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljs/ataru/virkailija/editor/handlers.cljs
Make e-mail previews follow form "hakeminen tunnistautuneena" setting.
> OY-4562 Use "form-allows-ht" parameter to display correct e-mail previews

- resources/less/virkailija-application.less
- src/cljs/ataru/virkailija/application/application_subs.cljs
- src/cljs/ataru/virkailija/application/information_request/virkailija_information_request_view.cljs
- src/cljs/ataru/virkailija/application/mass_information_request/virkailija_mass_information_request_view.cljs
- src/cljs/ataru/virkailija/application/mass_review/virkailija_mass_review_view.cljs
- src/cljs/ataru/virkailija/editor/subs.cljs
Ataru backend already silently fails to send messages to applicants if the user is not authorized to do so. Disable the relevant buttons in frontend when the user doesn't have any opo / editor / superuser rights, so the user won't even try to. 
Figuring out the exact rights especially for mass e-mails would require some help from the backend (new endpoint that matches the backend validations, possible performance issues because its always possible to filter application-by-application), so let's use somewhat more lax validations so that in some cases a user _may_ see enabled buttons even if they aren't allowed to complete the operation on the backend side.
> OY-4456 disable messaging buttons when user has no edit rights

- src/cljs/ataru/virkailija/application/view.cljs
Joissain tilanteissa lataus-spinneri meni pikselin murto-osan verran viewportin yli, vaikka sivu on vieritetty alas, eikä uusia rivejä näytetty ennen spinnerin klikkaamista. Korjattu lisäämällä pieni vakio offsettien vertailuun.
> OY-4472: Korjattu hakemusten käsittelyn listauksen lisärivien lataus vieritettäessä loppuun

- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/cljs/ataru/hakija/application_handlers.cljs
- src/cljs/ataru/hakija/application_view.cljs
The application doesn't get passed to frontend in case it's inactivated, so error message localization based on application language doesn't happen. 
When application has been inactivated, return the application language separately with the error, and use it for the error message in the frontend.
> OY-4627 use application language in error message when application inactivated

- src/clj/ataru/hakija/hakija_routes.clj
Spec: api/has-applied call should log the user / session identification data (eg. IP, browser, ...) to application logs for troubleshooting reasons.
> OY-4635 Add session and request data to has-applied application log

- resources/less/hakija.less
- src/cljs/ataru/hakija/application_hakukohde_component.cljs
Vastaava korjaus kuin 2. asteen hakukohdevalintaan, lisätty focus-tyylimääre, tabindex ja ruudunlukijateksti hakukohteiden järjestyksen vaihtoon (vrt https://github.com/Opetushallitus/ataru/pull/1479/files#diff-e91b5fdb0d7b9735f53d4a6b2cd8c7604b446211bfcdb0111d5f1d9f1c597a36)
> OY-4733 saavutettavuuskorjaus

- .gitignore
- resources/sql/form-queries.sql
- spec/ataru/fixtures/form.clj
- spec/ataru/fixtures/synthetic_application.clj
- spec/ataru/forms/form_access_control_spec.clj
- spec/ataru/hakija/hakija_routes_spec.clj
- spec/ataru/test_utils.clj
- spec/ataru/virkailija/virkailija_routes_spec.clj
- src/clj/ataru/applications/synthetic_application_util.clj
- src/clj/ataru/forms/form_access_control.clj
- src/clj/ataru/hakija/hakija_form_service.clj
- src/clj/ataru/kayttooikeus_service/kayttooikeus_service.clj
- src/clj/ataru/ohjausparametrit/mock_ohjausparametrit_service.clj
- src/clj/ataru/organization_service/organization_service.clj
- src/clj/ataru/person_service/person_integration.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
- src/clj/ataru/virkailija/authentication/auth_routes.clj
- src/clj/ataru/virkailija/virkailija_application_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/schema/form_element_schema.cljc
- src/cljc/ataru/schema/form_schema.cljc
- src/cljc/ataru/ssn.cljc
Move synthetic / external applications from haku-app to ataru.
Rolling TODO:
Are more thorough tests needed?
> OY-3070 Synthetic applications to ataru

- spec/ataru/suoritus/suoritus_service_spec.clj
- src/clj/ataru/odw/odw_service.clj
- src/clj/ataru/suoritus/suoritus_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
Lähtökoulu data shown on the application view was based on most recent lähtökoulu and hence could change after application time was over. 
After this change, the visible lähtökoulu is the (most recent) one that was valid on the application end date.
There are no changes in the application access control in this PR - as it was a bit more complex than imagined, it was split to another ticket so we can do some planning beforehand.
> OY-4565 Do lahtokoulu filtering based on cutoff date

- src/cljs/ataru/cljs_util.cljs
- src/cljs/ataru/virkailija/application/application_subs.cljs
- test/cljs/unit/ataru/cljs_util_test.cljs
Changes like [] -> nil or "" -> [] were shown in the virkailija application changeset UI. Hide those.
There are probably more changes that should be hidden as well (eg. empty arrays of empty strings / arrays etc.), but let's start carefully.
> OY-4718 hide empty application changes from the change UI

- spec/ataru/suoritus/suoritus_service_spec.clj
- spec/ataru/virkailija/virkailija_application_service_spec.clj
- src/clj/ataru/odw/odw_service.clj
- src/clj/ataru/suoritus/suoritus_service.clj
- src/clj/ataru/virkailija/virkailija_application_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/schema/form_schema.cljc
Spec: in case of peruskoulun jälkeisen koulutuksen yhteishaku, lähtökoulu cutoff date should be 1st of June of the application year. Otherwise the end of the application period.
+ Moved the logic from routes to service.
+ Renamed suoritus-service.opiskelija to opiskelijan-luokkatieto to better match data that is returned.
> OY-4800 Use 1st of June of application year as lähtökoulu cutoff date in yhteishaku

- src/cljs/ataru/application_common/application_field_common.cljs
- src/cljs/ataru/hakija/application.cljs
- test/cljs/unit/ataru/application_common/application_field_common_test.cljs
- test/cljs/unit/ataru/hakija/application_test.cljs
- test/cljs/unit/ataru/unit_runner.cljs
Previously only question group fields with allowed option values (eg. dropdowns, single selects, multiselects) were nil-padded in sanitization phase. Do the same nil padding for other formFields (eg. text fields) as well.
Also fixes a related issue where empty singleChoice fields were not initialized correctly (= in the same way as completely empty form) on form modification.
> OY-4756 do nil-padding for all form fields in sanitization phase

- spec/ataru/forms/form_payment_info_spec.clj
- spec/ataru/hakija/hakija_routes_spec.clj
- spec/ataru/virkailija/virkailija_routes_spec.clj
- src/clj/ataru/forms/form_payment_info.clj
- src/clj/ataru/hakija/hakija_form_service.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/schema/form_element_schema.cljc
- src/cljc/ataru/schema/form_schema.cljc
Hakemusmaksu is dynamically determined by haku & hakukohde properties, so add it to form and haku on the fly whenever needed.
Built on top of OK-485 which has the base functionality, see separate PR.
> OK-529 dynamically add hakemusmaksu to form data when editing / filling

- .clj-kondo/babashka/sci/config.edn
- .clj-kondo/babashka/sci/sci/core.clj
- .clj-kondo/rewrite-clj/rewrite-clj/config.edn
- resources/sql/application-queries.sql
- spec/ataru/fixtures/application.clj
- spec/ataru/fixtures/db/unit_test_db.clj
- spec/ataru/fixtures/form.clj
- spec/ataru/forms/form_payment_info_spec.clj
- spec/ataru/kk_application_payment/fixtures.clj
- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/forms/form_payment_info.clj
- src/clj/ataru/haku/haku_service.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/utils.clj
- src/clj/ataru/koodisto/koodisto_db_cache.clj
- src/clj/ataru/person_service/person_service.clj
- src/clj/ataru/tarjonta_service/kouta/kouta_client.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
- src/clj/ataru/tarjonta_service/tarjonta_client.clj
- src/clj/ataru/tarjonta_service/tarjonta_parser.clj
- src/cljc/ataru/schema/form_schema.cljc
Payment state setting logic for hakemusmaksu:
- Complete constraints for filtering which hakus are in scope of hakemusmaksu (application period, studies start period, higher education related parameters)
- Checks for EU citizenship and application level exemptions (Final exemption field naming and option parsing are TBD, this one's a collaborative best guess)
- Determine, resolve and set payment state for applicant with possible multiple OID aliases (Polling for payments will be done separately)
Whenever some important piece of data is missing (eg. no exemption question on application form, or missing koodisto), throw an exception instead of failing silently - otherwise we risk making wrong decisions on the state.
> OK-556 payment state logic for hakemusmaksu

- spec/ataru/tarjonta_service/hakuaika_spec.clj
- src/clj/ataru/tarjonta_service/hakuaika.clj
- toteutettu paikkakorjauksena, ataru käyttään edelleen Joda-kirjastoa, mutta isompi refaktorointi vaatisi kattavaa testaamista
> OY-4878 Muutetaan hakemuksen päivämäärien ja kellonaikojen aikavyöhykkeet UTC+X -muotoon

- dev-resources/sql/dev-form-queries.sql
- spec/ataru/fixtures/application.clj
- spec/ataru/fixtures/db/unit_test_db.clj
- spec/ataru/hakija/hakija_routes_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_store_spec.clj
- spec/ataru/virkailija/virkailija_routes_spec.clj
- src/clj/ataru/applications/application_access_control.clj
- src/clj/ataru/applications/application_service.clj
- src/clj/ataru/applications/filtering.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_routes.clj
- src/clj/ataru/haku/haku_service.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_store.clj
- src/clj/ataru/person_service/person_service.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
- src/clj/ataru/tilastokeskus/tilastokeskus_service.clj
- src/clj/ataru/valintapiste/valintapiste_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/schema/form_schema.cljc
- Add payment status and history to application data whenever required (when returning a submitted application to virkailija or hakija, when listing applications on the virkailija side)
- Minor: convert payment states and events back to kebab-case when querying from db (missing from previous PRs).
- Also includes filtering from https://github.com/Opetushallitus/ataru/pull/1604
> OK-576 payment status to applications

- resources/ataru-oph.properties
- src/clj/ataru/background_job/maksut_poller_job.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/application/review_states.cljc
- src/cljc/ataru/schema/maksut_schema.cljc
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/application/application_list/virkailija_application_list_view.cljs
- src/cljs/ataru/virkailija/application/application_review_view.cljs
- src/cljs/ataru/virkailija/application/application_selectors.cljs
- src/cljs/ataru/virkailija/application/handlers.cljs
- src/cljs/ataru/virkailija/application/mass_review/virkailija_mass_review_view.cljs
- src/cljs/ataru/virkailija/application/payment/payment_handlers.cljs
- src/cljs/ataru/virkailija/application/payment/payment_subs.cljs
- src/cljs/ataru/virkailija/application/payment/payment_view.cljs
Muutettu maksujen luonti ja haku käyttämään yleisiä rajapintoja, poistettu turhia mainintoja tutusta.
> Ok 540 paatosmaksullisen hakemuksen kasittely

- .github/workflows/build.yml
Docker-image-kakuttaja on tullut tiensä päähän ja nyt tämä actions-putki voi luoda itse tarvitsemansa dockerimagen, jolloin ulkoiset riippuvuudet vähenevät.
- Postgres rakennetaan pitkästä tavarasta - en saanut toimimaan ilman localen muokkausta edes initdb:n avulla (ICU, alpine). Flyway odottaa collationin olevan fi_FI, mutta pelkän kannan collation ei riitä, kun myös käyttöjärjestelmä pitää olla "linjassa"
- Redis vaihdettu uudempaan versioon 7 ja haetaan omasta repostaan, joka on pull-through cachetettu ecr public reposta
- hiekkalaatikko pidetty entisellään
> Vaihdetaan docker image

- spec/ataru/fixtures/application.clj
- spec/ataru/forms/form_payment_info_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- src/clj/ataru/forms/form_payment_info.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_maksut_poller_job.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
- src/clj/ataru/kk_application_payment/utils.clj
PR with several smaller fixes / improvements:
- Handle time zones better in payment due date (will be mainly used for display and reminder logic here) and first possible eligible admission start time 
- Enrich modified payment data info with applicant e-mail for sending notifications and creating payments
- Use correct exemption field name and exemption values (for testing for now - may still change before module goes to production?)
> OK-720 kk payment timezone fixes

- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- spec/ataru/person_service/person_integration_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
- src/clj/ataru/kk_application_payment/utils.clj
- src/clj/ataru/person_service/person_integration.clj
- src/cljc/ataru/translations/texts.cljc
The first kk payment state update was previously made only in the first scheduled run (eg. possibly the next morning). Trigger the first update run right after an ONR person with OID gets added to the application. 
Adds the option to trigger the single person update run with an application id: fetches the person oid and haku information via application, and runs the update iff haku requires application payments.
Also includes some other fixes for issues during testing:
- Notification e-mails now get proper recipient and subject
- Only Finnish citizens are exempt from payment without any extra forms
- First payment status update run is triggered right after a person OID gets attached to an application
> OK-738 Add initial update run after application has a person assigned

- spec/ataru/kk_application_payment/kk_application_payment_maksut_poller_job_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_maksut_poller_job.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
Whenever payment poller marks a person's application paid, trigger the status update run for person and term so that any dependent changes happen immediately (eg. other applications for the same term may be marked exempt from payment).
> OK-741 Trigger update run on payment paid

- resources/less/editor.less
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/editor/view.cljs
Whenever a form has one or more hakus attached that have kk application payment required,
- Indicate the payment requirement next to the haku information
- Hide the option of manually adding other payment types to the form
> OK-554 Payment indicator to form editor

- resources/less/hakija.less
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/hakija/application_view.cljs
- src/cljs/ataru/hakija/subs.cljs
Add an additional kk application payment info text to the application submitted confirmation screen - only displayed when the form has kk application payment enabled and the nationality of the applicant is not Finnish.
> OK-716 Applicant kk payment info text

- resources/ataru-oph.properties
- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
- src/clj/ataru/maksut/maksut_protocol.clj
- src/clj/ataru/maksut/maksut_service.clj
- src/cljc/ataru/schema/maksut_schema.cljc
Whenever a payment for a term is made, other payment invoices for the person and term should be invalidated to avoid accidental double payments. Here we call maksut with the relevant payment references / application keys, because only ataru holds the up to date information on person oid linkages and all that.
> OK-748 payment invalidation

- spec/ataru/kk_application_payment/kk_application_payment_store_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_store.clj
Yesql enjoys automatically interpreting PostgreSQL dates as a timestamps converted to UTC instead of LocalDate - which means dates are off in Finnish time. Always reinterpret the timestamps in Helsinki time zone.
> Fix due date timezone after db selects

- src/clj/ataru/virkailija/virkailija_routes.clj
On virkailija side, the UI displays an error whenever trying to resend a payment e-mail. This was fixed earlier, but erroneously committed to another branch that's still in review. This PR fixes the specific issue. We obviously don't get real status data from the e-mail job, so just return OK whenever there was no exception up to the creation of the job.
> Fix e-mail resend response

- .gitignore
- resources/sql/application-queries.sql
Queries that use latest_applications view end up being needlessly complicated and hard for psql query optimizer. This one ought to speed up a critical oft repeated query from ~6 sec to the 10-100ms bracket with a normal production-like database.
> Optimize get-latest-applications-for-kk-payment-processing not to use latest applications view

- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
Whenever a person is required to pay application payment, they are required to pay tuition fee if they get accepted as well. But only for studies that don't have Finnish and/or Swedish as one of the teaching languages.
Built directly on top of OK-770 to avoid conflicts in payment logic.
> OK-719 set tuition payment obligation together with kk application payment obligation

- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
Whenever the update job actually calls the update function for a person & term, there should be at least one returned new or existing payment. If some of the caches are still refreshing, the update function finds 0, which is an error we should retry on according to normal job retry schedule, so throw an exception.
> OK-784 Throw an exception when payment status updater returns zero payment states

- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_store.clj
- src/clj/ataru/kk_application_payment/utils.clj
- src/clj/ataru/ohjausparametrit/mock_ohjausparametrit_service.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
- src/cljc/ataru/component_data/kk_application_payment_module.cljc
Even when the exemption question is answered, making the applicant exempt from application payment, the required attachment must still be present and valid by the attachment deadline.
If one or more of the mandatory attachments in the module is marked incomplete or missing, and the attachment deadline for the admission has already passed, set payment required for the person.
> OK-770 attachment deadline logic for kk application payments

- resources/less/virkailija-application.less
- spec/ataru/virkailija/virkailija_routes_spec.clj
- src/clj/ataru/applications/application_store.clj
- src/clj/ataru/virkailija/virkailija_routes.clj
- src/cljc/ataru/translations/texts.cljc
- src/cljs/ataru/virkailija/application/mass_review/virkailija_mass_review_handlers.cljs
- src/cljs/ataru/virkailija/application/mass_review/virkailija_mass_review_view.cljs
UI part for mass inactivation tool according to Figma prototype. Built on top of OK-712 which contains the backend logic, with some slight changes to the API in this PR.
> OK-801 mass inactivation UI

- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- spec/ataru/test_utils.clj
- src/clj/ataru/kk_application_payment/utils.clj
- src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
Previously the grace days for kk application payment attachment deadlines were calculated from the start of the day. This PR makes the calculation work with the actual haku end times as specified.
As a side effect, calculating how many days the payments in applications will get updated after haku end also gets adjusted a bit.
Modified the relevant tests to adjust the system clock to make sure exact deadlines are obeyed.
> OK-814 use original time for attachment grace days in kk application payment logic

- spec/ataru/hakija/hakija_form_service_spec.clj
- src/clj/ataru/hakija/hakija_application_service.clj
- src/clj/ataru/hakija/hakija_form_service.clj
Includes some refactoring for the current non-editable field logic as suggested.
> OK-843 mark overdue application form fields as non-editable

- spec/ataru/applications/excel_export_spec.clj
- spec/ataru/fixtures/excel_fixtures.clj
- src/clj/ataru/applications/application_service.clj
- src/clj/ataru/applications/excel_export.clj
Vaatii alle [OY-5071](https://github.com/Opetushallitus/ataru):n muutokset, koskettu samoihin kohtiin siirto-rajapinnassa.
> OY-5079: Poista hylkäyksen syyt excelistä ja siirto-rajapinnasta, jos ei enää ei-hakukelpoinen

- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/person_service/person_integration.clj
- src/clj/ataru/person_service/person_service.clj
When the applicant is an EU citizen and identity is confirmed via VTJ, they should be automatically exempt from application payment.
> OK-740 automatically mark VTJ-yksilöity EU citizen as exempt from application payment

- spec/ataru/kk_application_payment/kk_application_payment_maksut_poller_job_spec.clj
- spec/ataru/kk_application_payment/kk_application_payment_spec.clj
- src/clj/ataru/kk_application_payment/kk_application_payment.clj
- src/clj/ataru/kk_application_payment/kk_application_payment_maksut_poller_job.clj
- src/cljc/ataru/schema/maksut_schema.cljc
- Automatically set new deadline (calculated normally from now onwards) whenever a payment moves back from eg. not required to awaiting state again, and there's already an existing payment - requires maksut https://github.com/Opetushallitus/maksut/pull/42
- Whenever an active / awaiting payment is missing maksut secret, sync and store it as part of maksut polling
> OK-815 extend deadline whenever creating a new kk-application-payment invoice

- .gitignore
- Makefile
- src/clj/ataru/applications/automatic_eligibility.clj
The `log/info` is probably written in the wrong place by accident.  `doall` expects its first argument to be (return) a number.  What happens with current code is an equivalent of:
```
atehwa@polokku:~/proj/ataru$ clojure
Clojure 1.10.2
(doall nil [1 2 3 4 5])
Execution error (NullPointerException) at user/eval1 (REPL:1).
null
```
> OY-5239: fix NullPointerExceptions in `automatic-eligibility-if-ylioppilas`

- resources/sql/tutkintojen-tunnustaminen-queries.sql
- src/clj/ataru/tutkintojen_tunnustaminen/tutkintojen_tunnustaminen_send_job.clj
- src/clj/ataru/tutkintojen_tunnustaminen/tutkintojen_tunnustaminen_store.clj
Liittyy TUTU hakemuksen lähettämiseen ks. https://github.com/Opetushallitus/ataru/pull/1723
Maakoodin lähettäminen osana kutsua osoittautui tarpeettomaksi, sillä saamme tarvittavat tiedot suoraan hakemukselta ja tutkinnoilta.
> OPHTUTU-236 Poistetaan tutu hakemuksen lähettämisestä maakoodi turhana
