Opetushallitus/ataru

resources/less/editor.less, resources/less/vars.less, src/cljs/lomake_editori/dev/lomake.cljs, src/cljs/lomake_editori/editor/core.cljs, src/cljs/lomake_editori/editor/handlers.cljs, src/cljs/lomake_editori/editor/view.cljs, src/cljs/lomake_editori/soresu/component.cljs, src/cljs/lomake_editori/soresu/edit.cljs
Let's merge current work in progress to master. This pull request is for review purposes.
=> Soresu in action

spec/lomake_editori/soresu/component_spec.clj, src/cljc/lomake_editori/soresu/component.cljc, src/cljs/lomake_editori/dev/lomake.cljs, src/cljs/lomake_editori/editor/core.cljs, src/cljs/lomake_editori/editor/handlers.cljs, src/cljs/lomake_editori/soresu/component.cljs
A prototype feature that adds new (currently hard-coded) elements to the form. Just the UI part, no save or anything yet. Also, all elements are textfields.
=> Add new elements to form

resources/less/editor.less, resources/less/vars.less, src/cljc/lomake_editori/soresu/component.cljc, src/cljs/lomake_editori/dev/lomake.cljs, src/cljs/lomake_editori/editor/component.cljs, src/cljs/lomake_editori/editor/core.cljs
This feature adds fine-tuned versions of text field and container elements that can be added to a form. They aren't yet responsive, though.
=> Fine-tuned version of text field and container elements

resources/less/editor.less, resources/less/vars.less, src/cljs/lomake_editori/editor/component.cljs, src/cljs/lomake_editori/editor/core.cljs
There isn't yet any logic in the UI elements. They'll be implemented in a separate branch.
=> Initial layout for the form editor view

resources/less/hakija.less, src/cljs/ataru/hakija/form_view.cljs, src/cljs/ataru/virkailija/editor/component.cljs
Field size is stored and affects hakija application
Defaults to M
=> Store field size

src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/form_view.cljs, src/cljs/ataru/hakija/hakija_ajax.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/virkailija_ajax.cljs
hakija needs separate handling of errors and special situations. There is no flasher in the UI.
=> Separate ajax clients

resources/less/hakija.less, resources/templates/hakija.html
Basic layout works on iphone ok-ish
=> Responsive application

resources/less/editor.less, src/cljc/ataru/virkailija/soresu/component.cljc, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/view.cljs
Places undo box after removed element
=> Undo aftermath

.gitignore, src/cljc/ataru/virkailija/editor/handlers_macros.cljc, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, test/cljs/unit/ataru/cljs_util_test.cljs, test/cljs/unit/ataru/unit_runner.cljs, test/cljs/unit/ataru/virkailija/editor/handlers_test.cljs
Ability to drag'n'drop components into section wrappers and from them to root level. No fancy animations just yet.
=> Initial drag'n'drop functionality

resources/less/editor.less, src/cljc/ataru/virkailija/editor/component_macros.cljc, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, test/cljs/unit/ataru/virkailija/editor/handlers_test.cljs
The drag'n'drop feature will now show user a dashed box between component, in place where the dragged component would be dropped at the current moment.
Also fixed simplified some of the logic that handles re-organizing of the components in the application state when the drop event occurs.
=> Enhanced drag'n'drop

config/defaults.edn, oph-configuration/config.edn.template, spec/ataru/person_service/client_spec.clj, spec/ataru/test_utils.clj, spec/ataru/virkailija_routes_spec.clj, src/clj/ataru/cas/client.clj, src/clj/ataru/hakija/hakija_routes.clj, src/clj/ataru/hakija/hakija_system.clj, src/clj/ataru/http/server.clj, src/clj/ataru/person_service/client.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/clj/ataru/virkailija/virkailija_system.clj
Resolve all OIDs that belong to a given username. Please note that the username might have multiple OIDs.
This API call also initializes new CAS session if one doesn't yet exist. Also a new CAS session is initialized (once) in case the old one is not valid anymore.
=> Person service client

resources/less/editor.less, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/view.cljs
We decided to make a generic undo later, this doesn't work consistently
=> Remove undo functionality and styles

src/clj/ataru/applications/excel_export.clj
Also sorts columns in .xls export by the order of fields in the (current state of the) form.
=> Form submit time to excel

spec/ataru/applications/excel_export_spec.clj, spec/ataru/fixtures/application.clj, src/clj/ataru/applications/excel_export.clj, src/clj/ataru/virkailija/virkailija_routes.clj
* Form metadata in separate sheet on .xlsx export (applications now on 2nd sheet)
* Nicer name for exported file (e.g. `24_Ullan-testi-salpauksen-pohja_2016-07-15_0945.xlsx`)
=> Excel form metadata

resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/handlers.cljs, src/cljs/ataru/virkailija/views/banner.cljs
=> Rationalize rest api

resources/less/application-common.less, resources/less/virkailija-application.less, resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs
Show event list and heading for the application in review (pref. name, last name, ssn)
=> Application review2

resources/less/virkailija-application.less, resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/db.cljs, src/cljs/ataru/virkailija/routes.cljs, src/cljs/ataru/virkailija/virkailija_ajax.cljs
=> Application review3

resources/less/editor.less, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/virkailija/editor/component.cljs
Henkilömoduuli luettelee lisättävät kentät editoripuolella ja kertoo että se lisätään automaattisesti lomakkeelle
=> Person module description

.gitignore, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/hakija/application_form_components.cljs
Add placeholder for birth-date
=> Placeholder technology

src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/routes.cljs
Fix form :content getting overwritten when loading form list in the editor/application side
- caused by two XHRs overwriting previously fetched data
=> Editor application details not showing

spec/ataru/codes_service/postal_code_client_spec.clj, src/clj/ataru/codes_service/postal_code_client.clj, src/clj/ataru/hakija/hakija_routes.clj, src/clj/ataru/hakija/hakija_system.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/virkailija/editor/component.cljs
Automatically populate fields in application: 
* Gender from SSN (if Finnish nationality is selected)
* Post office and home municipality from PO number
=> Infer gender and po in application

src/cljc/ataru/virkailija/editor/handlers_macros.cljc, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs
prevent OOB exceptions when dragging components
=> Fix component dragging index out of bounds

project.clj, src/clj/ataru/hakija/hakija_routes.clj, src/clj/ataru/virkailija/virkailija_routes.clj
- Log Schema validation failure stack traces and reasons
- Log requests
- Log other exceptions
=> Improve server logging

resources/less/hakija.less, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/hakija/subs.cljs
"New spec" logic for SSN->gender and PO number->PO name logic in application.
Also fixes to the invalid field display in header, which did not have correct information.
=> Fixes to gender and po

project.clj, src/clj/ataru/core.clj, src/clj/ataru/db/migrations.clj, src/clj/ataru/hakija/hakija_system.clj, src/clj/ataru/hakija/validator.clj, src/clj/ataru/virkailija/virkailija_system.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs
* Add option for foreigners to have Finnish SSN in personal info module
* Fix form section validations in application form view
* Migrate old forms to use new personal info module structure
=> Ssn for foreigners in person info module

resources/less/editor.less, resources/less/vars.less, src/cljc/ataru/koodisto/koodisto_whitelist.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs
Add a selection of koodisto fields to choose for options in dropdown & multiple choice fields.
Can be reviewed, but still pending:
* Browser tests
* Verification of actual koodistos to include in selection
* Maybe add the whitelisted koodistos to form validation?
=> More koodisto options

resources/less/editor.less, resources/less/hakija.less, resources/less/virkailija-application.less, resources/spec/virkailijaEditorSpec.js, src/clj/ataru/applications/excel_export.clj, src/clj/ataru/virkailija/user/form_access_control.clj, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/virkailija/editor/component.cljs
=> Repeating field

bin/phantomjs-runner.js, resources/spec/hakijaSpec.js, resources/spec/testRunner.js, resources/spec/util.js, resources/spec/virkailijaEditorSpec.js, resources/templates/hakija-test.html, resources/templates/virkailija-test.html, spec/ataru/browser_tests.clj, src/clj/ataru/hakija/email.clj, src/clj/ataru/hakija/hakija_routes.clj, src/clj/ataru/virkailija/virkailija_routes.clj
More UI tests for virkailija and now also tests for hakija side!
Further development ideas:
* Remove existing dependencies to live backends (mock API calls)
* Test application creation "correctly" (now only checks against frontend state) in virkailija app
* Improve coverage in general
* Fix TODOs
=> More ui tests

resources/less/editor.less, resources/less/hakija.less, resources/less/virkailija-application.less, resources/spec/virkailijaEditorSpec.js, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/virkailija/editor/component.cljs
Add info-element for information purposes.
=> Info element

resources/less/editor.less, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/view.cljs
Some UI fixes for form control buttons:
* Buttons are now styled `<a>`'s.
* They get different color while hovered.
=> UI fixes for form control buttons

project.clj, resources/less/vars.less, resources/less/virkailija-application.less, resources/spec/virkailijaApplicationHandlingSpec.js, resources/sql/form-queries.sql, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/forms/form_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/routes.cljs
List also deleted forms that have filled applications associated in the virkailija application listing, allowing those applications to be viewed.
=> Show applications for deleted forms

resources/sql/application-queries.sql, spec/ataru/applications/application_store_spec.clj, spec/ataru/applications/excel_export_spec.clj, spec/ataru/fixtures/application.clj, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/applications/excel_export.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/virkailija/application/view.cljs
Improves and fixes various issues with applications. Now most application functions are split based on whether they belong to a form or a hakukohde.
=> Fix application handling and listing

resources/less/editor.less, resources/less/virkailija-application.less, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/review_states.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/db.cljs
Filter applications based on review-state in application handling
=> Application state filtering

resources/sql/application-queries.sql, resources/templates/email_confirmation_template.html, resources/templates/email_confirmation_template_en.txt, resources/templates/email_confirmation_template_fi.txt, resources/templates/email_confirmation_template_sv.txt, resources/translations/email_confirmation.edn, src/clj/ataru/applications/application_store.clj, src/clj/ataru/db/migrations.clj, src/clj/ataru/hakija/application_email_confirmation.clj, src/clj/ataru/hakija/background_jobs/email_job.clj, src/clj/ataru/person_service/person_integration.clj
Also only one template for emails. Translations in a separate EDN file.
=> HTML email with edit link

resources/less/editor.less, resources/spec/hakijaSpec.js, resources/spec/virkailijaEditorSpec.js, spec/ataru/hakija/validator_spec.clj, spec/ataru/util_spec.clj, src/clj/ataru/hakija/validator.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/util.cljc, src/cljc/ataru/virkailija/component_data/component.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/followup_question.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/handlers.cljs, test/cljc/unit/ataru/fixtures/answer.cljc, test/cljc/unit/ataru/fixtures/person_info_form.cljc, test/cljs/unit/ataru/hakija/application_test.cljs
Add option to add a followup question component to dropdown elements
=> Followup field mark 2

resources/templates/virkailija.html, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/hakija/hakija_ajax.cljs, src/cljs/ataru/virkailija/virkailija_ajax.cljs
=> Enable CSRF double submit protection

dev-resources/sql/dev-form-queries.sql, resources/db/migration/V1_30__Drop_obsolete_application_id_from_review.sql, resources/db/migration/V1_31__Drop_obsolete_application_id_from_events.sql, resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/cljc/ataru/schema/form_schema.cljc
Review and events are not version-dependent
=> Remove application_id from reviews and events

resources/less/editor.less, resources/less/hakija.less, resources/less/mixins.less, resources/less/vars.less, resources/less/virkailija-application.less, src/clj/ataru/hakija/hakija_form_service.clj, src/cljs/ataru/hakija/application_view.cljs
Add information about the hakukohde to the form title. Also some LESS refactoring.
=> Haku info in form title

resources/db/migration/V1_32__change_received_review_state_to_unprocessed.sql, resources/db/migration/V1_33__change_received_new_review_state_in_events_to_unprocessed.sql, resources/less/virkailija-application.less, resources/spec/virkailijaApplicationHandlingSpec.js, resources/sql/application-queries.sql, spec/ataru/applications/application_store_spec.clj, spec/ataru/applications/excel_export_spec.clj, spec/ataru/fixtures/application.clj, src/clj/ataru/applications/application_store.clj, src/cljc/ataru/application/review_states.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/virkailija/application/view.cljs
New states, old states renamed
=> Application handling state changes

bin/start-dev-build.sh, resources/less/virkailija-application.less, resources/spec/virkailijaApplicationHandlingSpec.js, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/application_sorting.cljs, src/cljs/ataru/virkailija/db.cljs, src/cljs/ataru/virkailija/temporal.cljs
In application handling, application columns like time and score are now sortable
=> Sort application columns

resources/less/editor.less, resources/less/hakija.less, resources/spec/virkailijaEditorSpec.js, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/excel_export.clj, src/clj/ataru/db/migrations.clj, src/clj/ataru/hakija/application_email_confirmation.clj, src/clj/ataru/hakija/validator.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/util.cljc, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/followup_question.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, test/cljc/unit/ataru/fixtures/person_info_form.cljc
Allow multiple followup questions to be added.
Fixes adjacent question validation bugs
=> Multi followup questions

bin/cibuild.sh, bin/start-dev-build.sh, src/clj/ataru/hakija/validator.clj, src/cljs/ataru/application_common/application_field_common.cljs, src/cljs/ataru/application_common/application_readonly.cljs, src/cljs/ataru/hakija/application_handlers.cljs, test/cljc/unit/ataru/fixtures/answer.cljc
Store multiple select answers as an array, instead of a comma-delimited string.
Also some tweaks to dev build script.
=> Fix commas in multiple select field

resources/less/hakija.less, src/clj/ataru/files/file_store.clj, src/clj/ataru/hakija/hakija_routes.clj, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs
Decided we don't need this feature. Clean up the codebase a bit.
=> We don't need no updating attachments

resources/less/vars.less, resources/less/virkailija-application.less, resources/spec/virkailijaApplicationHandlingSpec.js, src/cljs/ataru/virkailija/application/view.cljs
Add a quick checkbox to turn off/on all filters when viewing applications
=> Multiselect application state filters

resources/less/hakija.less, resources/less/virkailija-application.less, src/cljc/ataru/application/review_states.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/application_view.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/hakija_readonly.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
Actually a bunch of things:
* New application review state: "valintaesitys".
* Increase the size of the application review notes textarea.
* Ensure all links in info fields have the `target=_blank` attribute.
* After editing application, don't show all uneditable (= person info) fields, but replace them with a generic notification about contacting the school one is applying to.
=> Valintaesitys application state

resources/less/hakija.less, resources/less/virkailija-application.less, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
=> Hakija attachment UI fixes 2

src/cljs/ataru/hakija/subs.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/subs.cljs
Testing on Jenkins: http://ataruci:8080/job/remove-reg-sub-raws-tests/1/
=> Use reg-sub now that we can

resources/less/virkailija-application.less, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
- Do we want green text when the scan is OK?
=> Virus scan virkailija status UI

resources/db/migration/V1_41__Create_indexes_for_fields_used_in_where_and_join_clauses.sql, resources/sql/application-queries.sql, resources/sql/form-queries.sql, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/forms/form_store.clj
Remove duplicate or unused sql code
Create indexes for fields used in joins and where clauses
=> Sql tuning

dev/clj/ataru/anonymizer/core.clj, resources/db/migration/V1_42__Update_missing_person_oids_for_hakija_updated_applications.sql, resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj
Application versions should always have a person_oid if a previous version has one
=> Fix person oid issue with versions

src/clj/ataru/config/url_helper.clj
Reverts Opetushallitus/ataru#240
=> Revert "Simplify URL helper"

resources/less/hakija.less, resources/less/vars.less, resources/less/virkailija-application.less, src/cljs/ataru/virkailija/editor/component.cljs
=> Markdown help popup

resources/less/hakija.less, src/clj/ataru/applications/application_store.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/application_view.cljc, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/application_view.cljs, src/cljs/ataru/hakija/subs.cljs
client and server-side prevention
=> Prevent modifying when application (review) in one of the completed states

resources/ataru-oph.properties, src/clj/ataru/files/file_store.clj, src/clj/ataru/hakija/background_jobs/attachment_finalizer_job.clj, src/clj/ataru/hakija/background_jobs/hakija_jobs.clj, src/clj/ataru/hakija/hakija_application_service.clj
There isn't much logging info for e.g. which attachments fail finalisation, so this is more of a happy path implementation.
=> Finalize attachments

resources/db/migration/V1_43__Add_ssn_as_denormalized_field_for_searches.sql, resources/db/migration/V1_44__Dig_ssn_from_answers_and_add_to_table_field.sql, resources/less/vars.less, resources/less/virkailija-application.less, resources/sql/application-queries.sql, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/ssn.cljc, src/cljs/ataru/virkailija/application/application_search_control.cljs, src/cljs/ataru/virkailija/application/application_search_control_handlers.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/routes.cljs
New tab for application handling: search with ssn
=> Search with ssn

src/clj/ataru/hakija/background_jobs/attachment_finalizer_job.clj
Requires https://github.com/Opetushallitus/liiteri/pull/37
=> Finalize params go into the body

resources/less/virkailija-application.less, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/core.cljs, src/cljs/ataru/virkailija/views/banner.cljs
Review box starts floating when it goes over the upper visible border
=> Floating review when scrolled under threshold

resources/spec/hakijaEditSpec.js, resources/spec/hakijaSpec.js, spec/ataru/hakija/application_validators_spec.clj, src/clj/ataru/hakija/validator.clj, src/cljc/ataru/email.cljc, src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/rules.cljs, test/cljc/unit/ataru/fixtures/first_name.cljc, test/cljs/unit/ataru/hakija/application_validators_test.cljs
Add validation for main first names in person-info-module (main first names need to be a subset of the first names)
=> Validate main first name

resources/spec/hakijaEditSpec.js, resources/spec/hakijaSpec.js, spec/ataru/fixtures/application.clj, spec/ataru/fixtures/form.clj, spec/ataru/hakija/application_validators_spec.clj, spec/ataru/hakija/hakija_routes_spec.clj, src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/koodisto/koodisto_codes.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/virkailija/component_data/person_info_module.cljc, src/cljs/ataru/application_common/application_field_common.cljs, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/rules.cljs, test/cljs/unit/ataru/hakija/application_validators_test.cljs
Add "country of residence" selection to person info module (defaults to Finland) with some dynamic fields (with fancy validation) to go along with it.
=> Country of residence

src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/subs.cljs, test/cljs/unit/ataru/hakija/application_test.cljs
Some older forms might not have all questions specified which are requited by validators.
=> Fix rule checking with older forms.

resources/less/editor.less, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs
Fix form field remove animaiton that used to fade up 'n' out over(under?) the above element.
=> Make form elements minimize in height then remove.

resources/spec/virkailijaApplicationHandlingSpec.js, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/routes.cljs
Add query params to url when applying filters or selecting an application in application handling so that the same view can be shared between users.
=> Shareable virkailija link

project.clj, spec/ataru/applications/excel_export_spec.clj, src/clj/ataru/applications/excel_export.clj, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/virkailija/editor/component.cljs
If application and form don't have hakukohteet answer/question use application hakukohde as asnwer.
=> Get missing hakukohde for excel export also.

project.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/util.cljc, src/cljc/ataru/virkailija/component_data/component.cljc, src/cljs/ataru/application_common/application_field_common.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/hakija_readonly.cljs, src/cljs/ataru/hakija/subs.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
The feature is not ready and it is not possible to create question groups in the application edit view. This pull request is created to avoid merge conflicts due to large and old-ish branch. Development will continue in another branch.
=> Initial question group support

src/clj/ataru/applications/excel_export.clj, src/cljs/ataru/virkailija/editor/components/toolbar.cljs
Format kysymyryhmä answers for excel export.
=> Kysymysryhma excel

src/cljs/ataru/hakija/application_handlers.cljs
Possibility to edit applications having question group. Supports following elements:
* dropdown
* multiple choice
* single-answer text fields.
=> Partial question group edit support

src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/preferred_name.cljc, src/cljs/ataru/hakija/rules.cljs
Preferred name didn't validate when editing hakemus. Should probably be real time validation to give feedback without having to focus our of the element?
=> Validate preferred name after first name changed.

spec/ataru/fixtures/application.clj, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_view.cljs
Show applicant's answers (as uneditable) even after application time has passed in application edit view.
Also various fixes to:
* Application time logic (when one is able to submit/edit applications)
* Tests regarding above
* Time (zone) formatting
=> Hle 86 always see own answers

resources/less/mixins.less, resources/less/virkailija-application.less, resources/spec/util.js, resources/spec/virkailijaApplicationHandlingSpec.js, resources/sql/application-queries.sql, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/application/review_states.cljc, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs
Adds "mass update application state" functionality to virkailija application handling.
=> Hle 128 mass set application states

resources/spec/virkailijaHakemusEditSpec.js, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_routes.clj, src/cljc/ataru/hakija/editing_forbidden_fields.cljc, src/cljc/ataru/hakija/onr_fields.cljc, src/cljs/ataru/hakija/application_form_components.cljs
Following fields should *not* be editable:
* Passport number
* National ID
* Native language
Following fields should be editable:
* Email
* Postal code
* Phone number
=> Certain person info fields to be editable

src/clj/ataru/background_job/email_job.clj
Katso https://github.com/Opetushallitus/viestintapalvelu/pull/23
=> Send email unsanitized

src/clj/ataru/applications/permission_check.clj, src/clj/ataru/virkailija/virkailija_routes.clj
Katso https://github.com/Opetushallitus/hakurekisteri/pull/86
=> Permission check should not be concerned with roles

src/clj/ataru/files/file_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/virkailija/application/handlers.cljs
Katso https://github.com/Opetushallitus/liiteri/pull/44
=> POST versio tiedostojen metadata API:sta

resources/less/editor.less, resources/less/hakija.less, resources/less/vars.less, resources/spec/virkailijaApplicationHandlingSpec.js, src/clj/ataru/hakija/hakija_form_service.clj, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/subs.cljs
Preiliminary commits. Pending UI work.
=> Hle 174 - Add hakukohde names to hakukohde specific questions.

resources/templates/email_edit_confirmation_template_en.html, resources/templates/email_edit_confirmation_template_fi.html, resources/templates/email_edit_confirmation_template_sv.html, resources/templates/email_submit_confirmation_template_en.html, resources/templates/email_submit_confirmation_template_fi.html, resources/templates/email_submit_confirmation_template_sv.html, src/clj/ataru/hakija/application_email_confirmation.clj
(cherry picked from commit d50538f8149dc332331dad02f473f93b750bb976)
=> Show hakemusnumero in all emails

resources/ataru-oph.properties, src/clj/ataru/koodisto/koodisto_db_cache.clj, src/clj/ataru/virkailija/user/organization_client.clj, src/cljc/ataru/koodisto/koodisto_codes.cljc, src/cljc/ataru/koodisto/koodisto_whitelist.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/hakija/application_form_components.cljs
Pari uutta "koodistoa" pohjakoulutusmoduulille.
=> Hle 301  uudet koodistot

resources/less/hakija.less, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_hakukohde_component.cljs, src/cljs/ataru/hakija/application_hakukohde_handlers.cljs, src/cljs/ataru/hakija/subs.cljs
Improve hakukohde listing performance by limiting results amount.
=> Hle 309  hakukohde search perf

resources/spec/hakijaHakukohteenHakuaikaSpec.js, resources/spec/util.js, src/cljs/ataru/hakija/application_hakukohde_component.cljs, src/cljs/ataru/hakija/application_hakukohde_handlers.cljs, src/cljs/ataru/hakija/application_view.cljs
.. also sort hakukohde listing alphabetically by label (HLE-325)
=> HLE-326: support multiple query terms in hakukohde search

resources/ataru-oph.properties, src/clj/ataru/applications/application_service.clj, src/clj/ataru/odw/odw_service.clj, src/clj/ataru/person_service/person_client.clj, src/clj/ataru/person_service/person_service.clj
ONR branch HLE-315 must be merged and installed in production before this one is put into production!
=> HLE 315 Use 'master' person versions from ONR.

resources/sql/application-queries.sql, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj
Extend valintalaskenta api params
=> Get valintalaskenta applications by application key also.

src/clj/ataru/applications/application_store.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_form_service.clj, src/clj/ataru/hakija/hakija_routes.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/util.cljc, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/application_view.cljs, src/cljs/ataru/hakija/core.cljs
Korjattu bugi ja muokattu jatkuvan haun esittämisen logiikkaa merkittävästi. Pientä siivoustakin samalla.
=> Hle 385  jatkuva haku editable

src/cljs/ataru/hakija/application_handlers.cljs
=> Use handle delete attachment to 'init' empty question group answer.

src/clj/ataru/applications/application_service.clj
Teksti "Tuntematon koodi xxx" koodeille jotka eivät löydy koodistosta.
=> Teksti koodistoon kuulumattomille koodeille

src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/application_common/fx.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/application_view.cljs, src/cljs/ataru/hakija/subs.cljs
NB: tarttis ruotsinnoksen vielä ennen mergeä
=> HLE-418 varoita sulkiessa muokattua ja tallentamatonta hakemusta

resources/less/hakija.less, resources/less/virkailija-application.less, src/cljc/ataru/util.cljc, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/hakija/application.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_hakukohde_component.cljs, src/cljs/ataru/hakija/hakija_readonly.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
=> Hle 417 - Fix wrapper section titles

src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_form_service.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/application_view.cljs
Don't allow editing of application submitted to form when in processing.
=> Don't allow editing when in processing

src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/subs.cljs
Tämmönen tuherrus jos ois käytännöllinen
=> Don't allow creating multiple base education modules.

resources/less/virkailija-common.less, src/cljs/ataru/virkailija/application/view.cljs
When a review note is an eligibility state note, show which hakukohde it concerns.
=> Show info on eligibility tooltip

bin/start-dev-build.sh, resources/less/virkailija-application.less, src/cljc/ataru/application/application_states.cljc, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs
Hakukohdevalinta vaikuttaa myös hakukohdekohtaisiin filtteröinteihin. Ei ota toistaiseksi kantaa hakukohderyhmiin.
=> HLE-459 hakemusrajaukset hakukohteittain

src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/organization_service/session_organizations.clj, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/views/banner.cljs
Actually limit rights when selecting acceess rights as superuser.
=> Fix selecting virkailija rights

src/cljs/ataru/virkailija/editor/view.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
=> links to tarjontaan (haku + hakukohde) added to hakemukset view.

src/clj/ataru/applications/application_store.clj, src/cljc/ataru/schema/form_schema.cljc
Katso https://github.com/Opetushallitus/hakurekisteri/pull/118
=> Tieto suoritetusta korkeakoulututkinnosta sureen

resources/less/hakija.less, resources/spec/virkailijaHakemusEditSpec.js, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_form_service.clj, src/clj/ataru/hakija/validator.clj, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/subs.cljs
* Näytä kaikki henkilötiedot (hetu, syntymäaika) virkailijan muokatessa hakemusta
* Salli henkilötietojen muokkaus virkailijalle, jos oppijanumero ei muodostunut
=> Hle 493 virkailijamuokkaus hlotiedot

spec/ataru/hakija/background_jobs/attachment_finalizer_job_spec.clj, spec/ataru/organization_service/organization_client_spec.clj, spec/ataru/organization_service/organization_service_spec.clj, spec/ohjausparametrit/ohjausparametrit_client_spec.clj, src/clj/ataru/background_job/email_job.clj, src/clj/ataru/cas/client.clj, src/clj/ataru/files/file_store.clj, src/clj/ataru/flowdock/flowdock_client.clj, src/clj/ataru/hakija/background_jobs/attachment_finalizer_job.clj, src/clj/ataru/koodisto/koodisto_db_cache.clj, src/clj/ataru/ohjausparametrit/ohjausparametrit_client.clj, src/clj/ataru/organization_service/organization_client.clj, src/clj/ataru/tarjonta_service/tarjonta_client.clj, src/clj/ataru/util/http_util.clj
Oisko tässä kaikki http-kutsujen paikat?
=> Refactor http requests to use wrapper with default headers.

src/clj/ataru/applications/application_store.clj, src/cljc/ataru/schema/form_schema.cljc
Tuotantoon samalla kuin henkilo-ui:n toisen pään toteutus.
=> Return nationality as array from onr api.

resources/less/virkailija-application.less, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/view.cljs
Samassa murupolkutyylinen kysymyksen nimi vastausmuutosnäkymään, HLE-691
=> Hle 673  vastausmuutosnakyman oikeat tekstit

src/clj/ataru/applications/application_store.clj
Siivun koko 10000 valittu haarukoimalla.
=> HLE-771 Partition valintalaskenta db query

resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/clj/ataru/odw/odw_service.clj, src/cljc/ataru/schema/form_schema.cljc
Katso myös https://github.com/Opetushallitus/hakurekisteri/pull/127
=> Hle 738  hle 770  hakukelpoisuudet sure ja odw

spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/files/file_store.clj
Katso https://github.com/Opetushallitus/liiteri/pull/46
=> Poikkeus jos metadatan lataus epäonnistuu

dev-resources/sql/anonymizer-application-queries.sql, dev/clj/ataru/anonymizer/anonymizer_application_store.clj, dev/clj/ataru/anonymizer/core.clj, project.clj, src/clj/ataru/db/migrations.clj
Katso https://github.com/Opetushallitus/cloud-base/pull/42
=> Hle 929  anonymisoi hakemus salaisuudet

dev/clj/ataru/anonymizer/core.clj
Katso https://github.com/Opetushallitus/cloud-base/pull/43
=> Anonymisoi liiteavaimet

resources/less/editor.less, resources/spec/virkailijaEditorSpec.js, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/drag_n_drop_spacer.cljs, src/cljs/ataru/virkailija/editor/components/followup_question.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/views/hakukohde_and_hakukohderyhma_search.cljs, test/cljs/unit/ataru/virkailija/editor/handlers_test.cljs
=> Hle 972  kysymyksen lukitseminen

resources/db/migration/V1_111__Reviewer_organization.sql, resources/db/migration/V1_112__application-event-virkailija-organizations.sql, resources/less/virkailija-application.less, resources/spec/virkailijaApplicationHandlingSpec.js, resources/sql/application-queries.sql, spec/ataru/tutkintojen_tunnustaminen_spec.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/application_store.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/util.cljc, src/cljs/ataru/virkailija/application/view.cljs
Muutoshistoriaan kirjataan virkailijan jokaisen erillisen korkeimman tason oikeuden tieto.
=> HLE-906: kirjataan virkailijan organisaatiotieto muutoshistoriaan

project.clj, spec/ataru/util/random_spec.clj, spec/ataru/util/secrets_generator.clj
Meinasin ensin tehdä secrettien generoinnin yksikkötestiin, joten tein testin, mutta sitten ajettava sovellus tuntuikin luontevammalta.
=> VTKU-51 : secret-generaattori + testi secretin generoinnille

resources/sql/application-queries.sql
When building the response for suoritusrekisteri, related to https://github.com/Opetushallitus/hakurekisteri/pull/193
=> BUG-2049 Use asiointikieli also from answers

resources/db/migration/V1_114__index_background_job_query.sql, resources/db/migration/V1_115__index_background_job_query.sql, resources/sql/background-job-queries.sql, src/clj/ataru/background_job/job.clj, src/clj/ataru/background_job/job_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj
Tausta-ajojen seurantakysely liian raskas
=> BUG-2068 - Seurantakysely

resources/spec/virkailijaEditorQuestionGroupSpec.js, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/virkailija/editor/component.cljs
Vierekkäisille tekstikentille vastaava toiminnallisuus kuin tekstikentille.
=> Oy 325 vierekkaisetkentat

resources/ataru-oph.properties, resources/less/hyvaksynnan-ehto.less, resources/less/virkailija-application.less, resources/less/virkailija-site.less, src/clj/ataru/tarjonta_service/tarjonta_service.clj, src/clj/ataru/valintaperusteet/client.clj, src/clj/ataru/valintaperusteet/service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/clj/ataru/virkailija/virkailija_system.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/application_common/fx.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/handlers.cljs, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/subs.cljs, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/view.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/core.cljs
Käyttää tässä https://github.com/Opetushallitus/valinta-tulos-service/pull/162 syntyviä uusi API:ja
=> HLE-1088  ehdollisesti hyvaksyttavissa

src/cljs/ataru/virkailija/application/application_subs.cljs
Tämän halutaan toimivan myös priorisoinnittomassa yhteishaussa.
=> HLE-1133 : Näytä ensisijaisuuskriteeri aina hakukohteilla rajattessa

src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs
Ei saa olla mahdollista muuttaa vastaanoton tai ilmoittautumisen tilaa, kun valinnan tila on "hylätty" tai "varalla". Ks. kuva:
=> HLE-1138: kun valinnan tila "hylätty" tai "varalla", sallitaan vain julkaisun tilan muutos

src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/cljs_util.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_handlers.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs, src/cljs/ataru/virkailija/application/view.cljs
Näytetään valinnan tilan muutokset muutoshistoriassa oheisen kuvan mukaisella tavalla:
=> HLE-1081: valinnan tila muutoshistoriassa

resources/ataru-oph.properties, spec/ataru/applications/excel_export_spec.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/excel_export.clj, src/clj/ataru/cas/client.clj, src/clj/ataru/valinta_tulos_service/service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/clj/ataru/virkailija/virkailija_system.clj, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/handlers.cljs, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/subs.cljs
Uudet VTS API:t syntyvät tässä https://github.com/Opetushallitus/valinta-tulos-service/pull/169
=> Hle 1093  ehdollinen exceliin

src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_handlers.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs
Katso myös https://github.com/Opetushallitus/valinta-tulos-service/pull/171
=> Hle 1154  kevytvalinta yps

src/clj/ataru/hakija/hakija_application_service.clj, src/cljc/ataru/translations/texts.cljc
Korjattu auditlogitus myöhästyneille hakemuksille, jotta ei synny "palvelinvirhettä" vaan saadaan palautettua oikea virhe.
=> Oy 335 hakuaikapaattynyt

resources/ataru-oph.properties, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/handlers.cljs
Katso https://github.com/Opetushallitus/valinta-tulos-service/pull/174
=> Ota käyttöön uusi ehdollisuuden muutoshistoria API

dev-resources/koodisto_service/codeelement/oppilaitostyyppi_21.json, dev-resources/koodisto_service/json/oppilaitosnumero/koodi.json, dev-resources/organisaatio_service/organisaatio/02439.json, spec/ataru/koodisto/koodisto_db_cache_spec.clj, src/clj/ataru/koodisto/koodisto_db_cache.clj
Pieni muutos tuotantokoodissa, isompi työ testeissä niin voi jatkossa tehdä suht nätisti testejä muillekin koodistoluokille.
=> HLE-1153: error handling for unresolvable institutions

spec/ataru/fixtures/db/browser_test_db.clj, src/clj/ataru/applications/application_store.clj
Also add one such char to test data.
=> BUG-2119 Filter char \u0000 from application answer values.

src/cljs/ataru/virkailija/application/view.cljs
Tila tallennetaan atomiin lomake-elementin ulkopuolella, mutta tätä tilaa ei otettu huomioon lomaketta renderöitäessä.
=> BUG-2156: initialize review selection checkbox with correct value

spec/ataru/odw/odw_service_spec.clj, src/clj/ataru/odw/odw_service.clj, src/clj/ataru/tarjonta_service/tarjonta_service.clj
These are a mix of existing default ones, new ids and ODW hardcoding values.
=> OY-342: Add new base education completion ids

oph-configuration/config.edn.template, src/cljs/ataru/hakija/application_form_components.cljs
Affects whether hakija will have the possibility to download
the attachment.
=> OY-362 Introduce :attachment-download-allowed feature flag

.clj-kondo.config.edn, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
Kerään tänne tekemiäni korjauksia clj-kondo:n varoitusten poistamiseksi.
=> Poista clj-kondon varoituksia

resources/templates/hakija.html
This is exactly the same snippet as used by omatsivut.
=> OY-355: Add Matomo tracking code

src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/belongs_to_hakukohteet_component.cljs, src/cljs/ataru/virkailija/editor/components/component_content.cljs, src/cljs/ataru/virkailija/editor/components/info_addon_component.cljs, src/cljs/ataru/virkailija/editor/components/input_field_component.cljs, src/cljs/ataru/virkailija/editor/components/input_fields_with_lang_component.cljs, src/cljs/ataru/virkailija/editor/components/markdown_help_component.cljs, src/cljs/ataru/virkailija/editor/components/repeater_checkbox_component.cljs, src/cljs/ataru/virkailija/editor/components/text_component.cljs, src/cljs/ataru/virkailija/editor/components/text_header_component.cljs, src/cljs/ataru/virkailija/editor/components/validator_checkbox_component.cljs
Tämän voi viedä masteriin vasta HLE-1209:n jälkeen.
=> Virkailija editorin text-component ja kumppanit erilleen omaan tiedostoon

resources/spec/virkailijaApplicationHandlingSpec.js, resources/spec/virkailijaEditorQuestionGroupSpec.js, resources/spec/virkailijaEditorSelectionLimitSpec.js, resources/spec/virkailijaEditorSpec.js
Korjauksia selaintesteihin. Nämä toistuvat systemaattisesti, kun selaintestejä ajaa verkkoliikenteen hidastuksella.
=> Korjaa selaintesteja

resources/less/arvosanat-hakija.less, resources/less/button-component.less, resources/less/dropdown-component.less, src/cljc/ataru/component_data/arvosanat_module.cljc, src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/application_common/components/button_component.cljs, src/cljs/ataru/application_common/components/dropdown_component.cljs, src/cljs/ataru/hakija/application_handlers.cljs, src/cljs/ataru/hakija/arvosanat/arvosanat_components.cljs, src/cljs/ataru/hakija/arvosanat/arvosanat_render.cljs, src/cljs/ataru/hakija/components/dropdown_component.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/hakija/schema.cljs
Testattavissa QA-ympäristössä.
=> HLE-1098: valinnaisen kielen lisäys arvosanalomakkeelle

cypress/hakijanNakyma.ts, cypress/integration/peruskoulunArvosanatSpec.ts, cypress/testit/arvosanat/peruskoulunArvosanatOsionHakijanLukunakymanTarkistaminen.ts, cypress/testit/hakemuksenLahettaminen.ts, src/cljc/ataru/component_data/arvosanat_module.cljc, src/cljc/ataru/schema/module_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/arvosanat/arvosanat_components.cljs, src/cljs/ataru/hakija/hakija_readonly.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/core.cljs
Lisäksi peruskoulun arvosanalomakkeen lukunäkymän testaus.
=> HLE-1101: 2. asteen arvosanalomake

cypress/hakijanNakyma.ts, cypress/testit/arvosanat/peruskoulunArvosanatOsionHakijanLukunakymanTarkistaminen.ts, cypress/testit/arvosanat/peruskoulunArvosanatOsionTayttaminenHakijana.ts, src/cljc/ataru/component_data/arvosanat_module.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/schema/module_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/arvosanat/arvosanat_components.cljs, src/cljs/ataru/hakija/arvosanat/arvosanat_render.cljs, src/cljs/ataru/hakija/components/dropdown_component.cljs, src/cljs/ataru/hakija/rules.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs
Käyttäjälle mahdollisuus ilmoittaa, mitä kieltä opiskellut esim. A1 aineen tapauksessa.
Lisäksi muutamia pienempiä korjauksia.
=> HLE-1250: oppiaineen lisääminen kieliaineisiin

.travis.yml, spec/ataru/applications/application_store_db_spec.clj, spec/ataru/applications/application_store_spec.clj, spec/ataru/fixtures/application.clj
Regressiotesti siltä varalta, että tämä menisi rikki HLE-1243 :n yhteydessä.
Siirsin samalla ainoan tietokantaan kirjoittavan testitapauksen vanhasta testistä tähän uuteen.
=> HLE-1263 : Testaa liitteen tilalla hakeminen

spec/ataru/applications/application_store_spec.clj, src/clj/ataru/applications/application_store.clj
redux branch, with less rebasing confusion
=> BUG-2110: fix payment obligation automation modification logic to switch between unreviewed and not-obligated

spec/ataru/applications/answer_util_spec.clj, src/clj/ataru/applications/answer_util.clj
=> OY-406 Add suoritusvuosi for avoin kk pohjakoulutus for ODW

resources/sql/form-queries.sql, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/forms/form_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj
Returns only forms that use given hakukohderymä
=> HLE-1374 Add query-param to filter forms with hakukohderyhma

resources/less/hakija.less
* Make body text darker
* Make link text lighter
* Add underline to links
https://webaim.org/resources/linkcontrastchecker/?fcolor=4C4C4C&bcolor=FFFFFF&lcolor=3A7A10
=> HLE-1467: Improve link accessibility

src/clj/ataru/tarjonta_service/kouta/kouta_client.clj
Näin vääränmittaiset oidit päädytään käsittelemään samoin kuin 404-vastaukset eli palautetaan nil.
=> OY-3190 Only make kouta calls with the right oid length

cypress/checkbox.ts, cypress/fixtures/uusiLomake.json, cypress/fixtures/uusiLomakeArkaluontoinenVastaus.json, cypress/hakijanNakyma.ts, cypress/integration/hakemuksenMuokkausSpec.ts, cypress/integration/painikkeetYksiValittavissaKoodistostaSpec.ts, cypress/reitit.ts, resources/less/hakija.less, resources/spec/virkailijaEditorQuestionGroupSpec.js, resources/spec/virkailijaEditorSelectionLimitSpec.js, resources/spec/virkailijaEditorSpec.js, spec/ataru/fixtures/application.clj, spec/ataru/fixtures/form.clj, spec/ataru/hakija/hakija_form_service_spec.clj, spec/ataru/hakija/hakija_routes_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_form_service.clj, src/cljc/ataru/component_data/component.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/checkbox_component.cljs, src/cljs/ataru/virkailija/editor/components/text_component.cljs
https://jira.eduuni.fi/browse/HLE-1105
=> Hle 1105 arkaluontoiset

resources/less/editor.less, resources/less/hakija.less, resources/spec/virkailijaEditorQuestionGroupSpec.js, resources/spec/virkailijaEditorSpec.js, src/clj/ataru/hakija/validator.clj, src/cljc/ataru/component_data/component.cljc, src/cljc/ataru/hakija/application_validators.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/schema/modal_info_element_schema.cljc, src/cljc/ataru/schema/params_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljc/ataru/util.cljc, src/cljc/ataru/virkailija/editor/form_utils.cljc, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_view.cljs, src/cljs/ataru/hakija/hakija_readonly.cljs, src/cljs/ataru/hakija/subs.cljs, src/cljs/ataru/virkailija/application/hyvaksynnan_ehto/handlers.cljs, src/cljs/ataru/virkailija/editor/component.cljs, src/cljs/ataru/virkailija/editor/components/modal_info_element.cljs, src/cljs/ataru/virkailija/editor/components/prevent_submission_component.cljs, src/cljs/ataru/virkailija/editor/components/toolbar.cljs, src/cljs/ataru/virkailija/editor/core.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
https://jira.eduuni.fi/browse/HLE-1285
=> HLE-1285: Dropdown option can prevent form submission

resources/less/hakija.less, src/cljs/ataru/application_common/components/button_component.cljs, src/cljs/ataru/hakija/application_hakukohde_2nd_component.cljs
https://jira.eduuni.fi/browse/HLE-1482
=> Add label for hakukohde_2nd_component koulutustyyppi-rajain button

src/cljc/ataru/application/review_states.cljc, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/editor/subs.cljs
https://jira.eduuni.fi/browse/HLE-1573
=> HLE-1573: Disable processing-state and hakukohde selection for opo

resources/less/virkailija-application.less, spec/ataru/hakija/hakija_form_service_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/hakija/hakija_form_service.clj, src/clj/ataru/hakija/toisen_asteen_yhteishaku_logic.clj, src/clj/ataru/tutkintojen_tunnustaminen.clj, src/cljc/ataru/application/review_states.cljc, src/cljc/ataru/hakija/person_info_fields.cljc, src/cljc/ataru/util.cljc, src/cljs/ataru/hakija/application_hakukohde_2nd_component.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/view.cljs, src/cljs/ataru/virkailija/editor/subs.cljs
Toteuttaa tiketit:
* https://jira.eduuni.fi/browse/HLE-1526
* https://jira.eduuni.fi/browse/HLE-1552
* https://jira.eduuni.fi/browse/HLE-1563
=> HLE-1526: Käyttöoikeudet toisen asteen yhteishaun hakemusten käsittelyssä

src/cljc/ataru/util.cljc, src/cljs/ataru/hakija/application/field_visibility.cljs, src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
https://jira.eduuni.fi/browse/HLE-1565
=> HLE-1565: Respect section visibility conditions in application handling

spec/ataru/user_rights_spec.clj, src/clj/ataru/haku/haku_service.clj, src/cljc/ataru/user_rights.cljc, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/views.cljs
https://jira.eduuni.fi/browse/HLE-1585
=> HLE-1585: Opinto-ohjaaja käyttöoikeuden muutos

src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/koodisto/koodisto_db_cache.clj, src/cljc/ataru/util.cljc
https://jira.eduuni.fi/browse/HLE-1576
=> HLE-1576: Remove duplicate applications from view

src/clj/ataru/applications/application_access_control.clj
https://jira.eduuni.fi/browse/HLE-1588
=> HLE-1588: Preserve order when removing duplicate applications

src/cljs/ataru/virkailija/application/application_subs.cljs
https://jira.eduuni.fi/browse/HLE-1584
=> HLE-1584: Application notes can be edited without edit rights

resources/ataru-oph.properties, resources/less/virkailija-application.less, src/clj/ataru/suoritus/suoritus_client.clj, src/clj/ataru/suoritus/suoritus_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/view.cljs
https://jira.eduuni.fi/browse/HLE-1560
=> HLE-1560: Näytä lähtökoulu ja -luokka hakemuksella

spec/ataru/hakija/hakija_application_service_spec.clj, src/clj/ataru/hakija/hakija_application_service.clj
https://jira.eduuni.fi/browse/HLE-1594
=> HLE-1594: Unable to remove and add same hakukohde

src/clj/ataru/applications/suoritus_filter.clj, src/clj/ataru/organization_service/organization_selection.clj, src/clj/ataru/organization_service/organization_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/virkailija/editor/handlers.cljs
https://jira.eduuni.fi/browse/HLE-1596
=> HLE-1596: Add missing oppilaitostyyppi and luokkataso to lähtökoulu filter

src/cljs/ataru/hakija/application_handlers.cljs
https://jira.eduuni.fi/browse/HLE-1593
=> HLE-1593: Clear followup values also outside question groups

src/cljs/ataru/virkailija/views/virkailija_readonly.cljs
https://jira.eduuni.fi/browse/HLE-1589
=> HLE-1589: Remove unasked questions in application handling

src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/view.cljs
https://jira.eduuni.fi/browse/HLE-1602
=> HLE-1602: Use haku of selected application for edit restrictions

src/clj/ataru/applications/application_service.clj
https://jira.eduuni.fi/browse/HLE-1609
=> HLE-1609: Fix excel export for opinto-ohjaaja

src/clj/ataru/applications/application_service.clj, src/clj/ataru/suoritus/suoritus_client.clj, src/clj/ataru/suoritus/suoritus_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljs/ataru/virkailija/application/handlers.cljs
Sisältää korjaukset:
* https://jira.eduuni.fi/browse/HLE-1608
* https://jira.eduuni.fi/browse/HLE-1610
=> HLE-1608: Fixes for lähtökoulu

src/clj/ataru/haku/haku_service.clj
https://jira.eduuni.fi/browse/HLE-1619
=> HLE-1619: Don't process haku which is not toisen asteen yhteishaku for opinto-ohjaaja

spec/ataru/applications/harkinnanvaraisuus/harkinnanvaraisuus_filter_spec.clj, spec/ataru/applications/harkinnanvaraisuus/harkinnanvaraisuus_util_spec.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/applications/harkinnanvaraisuus/harkinnanvaraisuus_filter.clj, src/clj/ataru/tarjonta_service/kouta/kouta_client.clj, src/clj/ataru/valintalaskentakoostepalvelu/pohjakoulutus_toinen_aste.clj, src/clj/ataru/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu_client.clj, src/clj/ataru/valintalaskentakoostepalvelu/valintalaskentakoostepalvelu_service.clj, src/clj/ataru/virkailija/virkailija_system.clj, src/cljc/ataru/application/harkinnanvaraisuus/harkinnanvaraisuus_types.cljc, src/cljc/ataru/application/harkinnanvaraisuus/harkinnanvaraisuus_util.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc
Sisältää toteutukset tiketeille:
* https://jira.eduuni.fi/browse/HLE-1615
* https://jira.eduuni.fi/browse/HLE-1621
=> HLE-1615: use new harkinnanvaraisuus flag

src/clj/ataru/applications/application_service.clj
https://jira.eduuni.fi/browse/HLE-1637
=> Don't try to assoc toinen aste data for all applications

resources/less/hakija.less, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/application_common/accessibility_util.cljs, src/cljs/ataru/hakija/application_form_components.cljs, src/cljs/ataru/hakija/application_hakukohde_2nd_component.cljs, src/cljs/ataru/hakija/application_hakukohde_component.cljs
Sisältää tiketit:
https://jira.eduuni.fi/browse/OY-3766
https://jira.eduuni.fi/browse/OY-3765
https://jira.eduuni.fi/browse/OY-3757
=> Oy 3757 notification contrast

src/clj/ataru/cache/caches.clj, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/routes.cljs
https://jira.eduuni.fi/browse/OY-4143
=> Oy 4143 fix questions not showing

spec/ataru/applications/question_util_spec.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/applications/question_util.clj, src/cljc/ataru/schema/form_schema.cljc
https://jira.eduuni.fi/browse/OY-4174
=> Mapping form keys for ammatillinen sport questions

resources/ataru-oph.properties, resources/less/virkailija-banner.less, spec/ataru/applications/application_access_control_spec.clj, spec/ataru/organization_service/organization_client_spec.clj, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/organization_service/organization_client.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/views/banner.cljs
https://jira.eduuni.fi/browse/OY-4217
=> Oy 4217 excel auth fix

.github/workflows/build.yml
=> replace c++ node nvm build with official action

src/cljc/ataru/component_data/base_education_continuous_admissions_module.cljc
https://jira.eduuni.fi/browse/OY-4216
=> Käytä pohjakoulutukselle samaa avainta kuin yhteishaussa

resources/less/virkailija-application.less, src/cljs/ataru/virkailija/application/application_list/virkailija_application_list_view.cljs
Add haku name to the application list search result rows, but only if no haku is specifically selected.
=> OY-4326 haku names to search results

spec/ataru/applications/question_util_spec.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/applications/question_util.clj, src/cljc/ataru/component_data/base_education_module_2nd.cljc
https://jira.eduuni.fi/browse/OY-4252
=> Kovakoodatut avaimet toisen asteen lomakkeelle

cypress/integration/kylmaLomakeSpec.ts, cypress/lomakkeenMuokkaus.ts, spec/ataru/forms/form_access_control_spec.clj, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_element_schema.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_view.cljs, src/cljs/ataru/hakija/subs.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/editor/view.cljs
https://jira.eduuni.fi/browse/OY-4283
=> Oy 4283 close cold form

src/cljs/ataru/hakija/application/field_visibility.cljs, test/cljs/unit/ataru/hakija/application/field_visibility_test.cljs
https://jira.eduuni.fi/browse/OY-4437
=> Fix option not being hidden in hakija

spec/ataru/person_service/person_integration_spec.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/person_service/person_integration.clj, src/clj/ataru/person_service/person_service.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/application_review_view.cljs
Some special ONR person sync cases already show up in the application logs. Make them show up in application events list as well.
NB! Requires new translations!
=> OY-4441 add application events for ONR person sync special cases

cypress/testit/lomake-elementit/painikkeetYksiValittavissaKoodistostaHakijalle.ts, resources/less/button-component.less, resources/less/hakija.less, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/hakija/application_hakukohde_2nd_component.cljs, src/cljs/ataru/hakija/banner.cljs
Saavutettavuusparannuksia
- Ruudunlukijaselite virheellisten kenttien lukumäärälle
- Hakukohteiden järjestystä vaihtaville nuolille ruudunlukijaselitteet 
- Kohdistuksen näyttävälle värille selkeämpi kontrasti
=> Oy 4538 accessibility

src/cljs/ataru/virkailija/application/application_review_view.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs
https://jira.eduuni.fi/browse/OY-4605
=> OY-4605: Älä näytä kevytvalintaa jos henkilöä ei ole yksilöity

.github/workflows/build.yml
Update tools and switch build into shared workflow - build x86 and ARM64
=> Arm64 reusable workflow

cypress/fixtures/valinnantulokset.json, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_handlers.cljs, src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_subs.cljs, test/cljs/unit/ataru/unit_runner.cljs, test/cljs/unit/ataru/virkailija/kevyt_valinta/virkailija_kevyt_valinta_subs_test.cljs
Vaatii VTS-muuutoksen: https://github.com/Opetushallitus/valinta-tulos-service/pull/370
=> OY-4421: Feikkaa vastaanoton tila jos aikaraja mennyt

spec/ataru/hakija/validator_spec.clj, src/clj/ataru/hakija/validator.clj
=> OY-4754 korjattu ClassCastException

src/clj/ataru/harkinnanvaraisuus/harkinnanvaraisuus_job.clj
Katselmoitu, renamettu branch.
=> Oy 4752 attempt to fix harkinnanvaraisuus job check bug

spec/ataru/applications/excel_export_spec.clj, spec/ataru/fixtures/excel_fixtures.clj, src/clj/ataru/applications/excel_export.clj, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/excel_download/excel_view.cljs, test/cljs/unit/ataru/virkailija/application/excel_download/excel_utils_test.cljs
- Lisätty puuttuvat lisäkysymykset (myös hakukohdekohtaiset)
- Korjattu Excel-rajainten käännösten hakeminen käyttäjän kielellä
=> OY-4788: Excel-export korjauksia

README.md, pom.xml, project.clj, resources/sql/application-queries.sql, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/odw/odw_service.clj, src/clj/ataru/tilastokeskus/tilastokeskus_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc
Puuttuvia tietoja joita tilastokeskus kaipaili: harkinnanvarainen_valinta, hakijan_koulusivistyskieli, pohjakoulutus_2aste ja lahtokoulun_organisaatio_oid
=> OY-4828 lisää tietoja tilastokeskus-rajapintaan

README.md
...for the future developing & debugging generations.
=> Add tip about focus-it to README

src/clj/ataru/tilastokeskus/tilastokeskus_service.clj, src/clj/ataru/util/http_util.clj
Harkinnanvaraisuustiedoille käyttöön cachetettu rajapinta joka hakee osissa. Kasvatettu socket timeoutin aikarajaa ja pienennetty koostepalvelun batch-kokoa
=> Oy 4899 tuunaus

Makefile, Makefile.md, README.md, bin/run-integration-tests-in-ci.sh
Update Docker Compose (command) from v1 to v2 due to underlying image / package changes.
=> OY-4905 replace docker-compose with docker compose

config/defaults.edn, oph-configuration/config.edn.template, playwright/tests/editori-lomake-yleiset.spec.ts, playwright/tests/editori-maksutiedot.spec.ts, playwright/tests/virkailija-editor.spec.ts, resources/less/editor.less, spec/ataru/forms/form_payment_info_spec.clj, spec/ataru/hakija/hakija_routes_spec.clj, spec/ataru/virkailija/virkailija_routes_spec.clj, src/clj/ataru/forms/form_access_control.clj, src/clj/ataru/forms/form_payment_info.clj, src/clj/ataru/tarjonta_service/tarjonta_parser.clj, src/cljc/ataru/schema/form_element_schema.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/schema/maksut_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljc/ataru/virkailija/editor/form_diff.cljc, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/subs.cljs, src/cljs/ataru/virkailija/editor/view.cljs
Lisätty lomake-editorin yleisiin asetuksiin maksutiedon asettaminen (astu ja tutu), vaatii rekisterinpitäjän oikeudet muuttaa.
=> OK-574 Maksutiedon lisääminen lomakkeelle

spec/ataru/hakija/hakija_routes_spec.clj, spec/ataru/kk_application_payment/kk_application_payment_spec.clj, spec/ataru/kk_application_payment/kk_application_payment_store_spec.clj, spec/ataru/virkailija/virkailija_routes_spec.clj, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/filtering.clj, src/clj/ataru/kk_application_payment/kk_application_payment.clj, src/clj/ataru/person_service/person_service.clj, src/clj/ataru/tilastokeskus/tilastokeskus_service.clj, src/clj/ataru/valintapiste/valintapiste_service.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc
- Filter out applications awaiting payment from necessary APIs
- Add rudimentary filtering by kk payment state to the application list API (enables virkailija side UI list filtering later)
Built on top of https://github.com/Opetushallitus/ataru/pull/1583
=> OK-623 filter by payment status

src/cljs/ataru/virkailija/application/kevyt_valinta/virkailija_kevyt_valinta_handlers.cljs
Ei tyhjennetä kevyt-valinta tietoja turhaan
=> OY-4716 Kevytvalinnassa voi muokata valinnan tiloja liian nopeasti

resources/sql/maksut-queries.sql
Maksut poller hakee hakemukset myös lomakkeen maksutiedon perusteella
=> OK-540 Maksut poller hakee hakemukset myös lomakkeen maksutiedon perusteella

resources/ataru-oph.properties, src/cljc/ataru/schema/maksut_schema.cljc, src/cljs/ataru/virkailija/application/application_selectors.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/payment/payment_handlers.cljs, src/cljs/ataru/virkailija/application/payment/payment_view.cljs
Muutettu metadata skeemaa, url maksut fronttiin tukemaan uutta lokalisoitua pathia, refaktorointia.
=> Ok 662 astu lomakkeen nimi maksulle

resources/sql/application-queries.sql, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj
- Ei virhettä, jos haetaan nimellä, jossa on whitespace-merkkejä
- Lisätty henkilötunnuksella ja henkilön OID:lla hakeminen
=> OK-670: Paranneltu valinta-ui:n hakemukset-rajapintaa

resources/sql/application-queries.sql, src/cljc/ataru/schema/form_schema.cljc
Muutettu omatsivut application query palauttamaan lomakkeen nimi ja myös hauttomat hakemukset sekä samat muutokset schemaan.
=> OK-483 Hakemukset ilman hakua omille sivuille

spec/ataru/kk_application_payment/kk_application_payment_spec.clj, src/clj/ataru/kk_application_payment/kk_application_payment.clj, src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj, src/clj/ataru/tarjonta_service/mock_tarjonta_service.clj
Pass metadata about the admission and studies' start season inside maksut invoice request. Meant mainly for display data on the maksut pages and receipt.
=> OK-715 Add kk payment metadata for maksut

resources/less/editor.less, resources/templates/astu_decision_email_template.html, src/clj/ataru/email/application_email.clj, src/clj/ataru/forms/form_payment_info.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_element_schema.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/schema/maksut_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/payment/payment_handlers.cljs, src/cljs/ataru/virkailija/editor/handlers.cljs, src/cljs/ataru/virkailija/editor/view.cljs
Lisätty ASTU-lomakkeille ALV:n ja tarkemman maksuviitteen asettaminen.
=> OK-625 alv astumaksuille

resources/less/virkailija-application.less, spec/ataru/virkailija/virkailija_routes_spec.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/hakija/hakija_application_service.clj, src/clj/ataru/kk_application_payment/kk_application_payment.clj, src/clj/ataru/kk_application_payment/kk_application_payment_maksut_poller_job.clj, src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj, src/cljc/ataru/application/review_states.cljc, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/application_review_view.cljs, src/cljs/ataru/virkailija/application/application_selectors.cljs, src/cljs/ataru/virkailija/application/handlers.cljs, src/cljs/ataru/virkailija/application/payment/payment_handlers.cljs, src/cljs/ataru/virkailija/application/payment/payment_subs.cljs, src/cljs/ataru/virkailija/application/payment/payment_view.cljs, src/cljs/ataru/virkailija/db.cljs
- Rest of the virkailija texts and translations
- Minor fixes and optimizations too small to work on separately
=> OK-745 kk payment translations and fixes

src/cljc/ataru/schema/form_schema.cljc
=> OY-5045 Ataru hyväksymään preview-generation tilassa "started" olevat liitteet

resources/templates/email_kk_payment_link_en.html, resources/templates/email_kk_payment_link_fi.html, resources/templates/email_kk_payment_link_sv.html, resources/templates/email_kk_payment_reminder_en.html, resources/templates/email_kk_payment_reminder_fi.html, resources/templates/email_kk_payment_reminder_sv.html, spec/ataru/kk_application_payment/kk_application_payment_status_updater_job_spec.clj, src/clj/ataru/kk_application_payment/kk_application_payment_status_updater_job.clj, src/clj/ataru/kk_application_payment/utils.clj
=> OK-842 add application key to payment mails

config/cypress.ci.edn, config/cypress.edn, config/defaults.edn, config/dev.edn, config/test.edn, oph-configuration/config.edn.template, resources/db/migration/V20242812000000__add_reminder_fields_to_information_request.sql, resources/less/virkailija-application.less, resources/sql/information-request-queries.sql, spec/ataru/information_request/fixtures.clj, spec/ataru/information_request/information_request_spec.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/information_request/information_request_reminder_job.clj, src/clj/ataru/information_request/information_request_service.clj, src/clj/ataru/information_request/information_request_store.clj, src/clj/ataru/virkailija/background_jobs/virkailija_jobs.clj, src/clj/ataru/virkailija/virkailija_routes.clj, src/cljc/ataru/schema/form_schema.cljc, src/cljc/ataru/translations/texts.cljc, src/cljs/ataru/virkailija/application/application_review_view.cljs, src/cljs/ataru/virkailija/application/application_subs.cljs, src/cljs/ataru/virkailija/application/handlers.cljs
Mahdollisuus asettaa automaattinen muistutusviestin lähetys täydennyspyynnölle.
=> OK-696 automaattinen muistutus taydennyspyyntoon

spec/ataru/tutkintojen_tunnustaminen_spec.clj, src/clj/ataru/tutkintojen_tunnustaminen.clj
Tarkistetaan myös lomakkeen maksutiedot eikä vain vanhaa konfiguraatiosta löytyvää oid-listaa.
=> OY-5123 ASHA siirrot tutu-maksu tiedon perusteella

src/clj/ataru/applications/question_util.clj
... perusopetuksen jälkeisen koulutuksen kevään 25 yhteishaussa
=> OY-5158: ota huomioon uudet kaksoistutkintoavaimet

resources/db/migration/V20250430000000__recreate_applications_hakukohde_index.sql, resources/sql/application-queries.sql, spec/ataru/virkailija/virkailija_routes_spec.clj, src/clj/ataru/applications/application_access_control.clj, src/clj/ataru/applications/application_service.clj, src/clj/ataru/applications/application_store.clj, src/clj/ataru/virkailija/virkailija_routes.clj
koostepalvelun muutosta varten: https://github.com/Opetushallitus/valintalaskentakoostepalvelu/pull/224
=> OY-5148: uusi rajapinta hakemus-oidien hakemista varten
